### ISSUE TITLE
PopUp Articoli

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#1]
### Steps to reproduce the issue
Creo due articoli: un articolo principale e un secondo articolo; all'interno dell'articolo principale inserisco il link al secondo articolo; il link è configurato in modalità popup, utilizzando la funzionalità di JCE MediaBox.
Esempio di articolo in finestra popup:
[pagina di esempio](https://antoniotodaro.it/verdellinopa/aree-del-personale/dirigenza/staff)

### Expected result
Dettagli articoli e icone secondo la formattazione del template; il font del testo dell'articolo il titillium web; ci si aspetta lo stesso tipo di visualizzazione del singolo articolo.

### Actual result
Icone stampa, email non presenti; info e testo articolo con font non titillium.

### System information (as much as possible)
Joomla! 3.8.2
Template 3.8.0.1

**Comment by eshiol** [comment]
verificare #73

**Comment by atodaro** [comment]
Verificato il corretto funzionamento in [articolo test](https://paswjoomla.net/ItaliaPAsW/aree-del-personale/docenti-e-ata/circolari-e-comunicazioni/2475-test-popup-ad-articolo)
