### ISSUE TITLE
Voce di menu - Icons

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#100]
### Steps to reproduce the issue

**Tipo di voce di menu** Tutti i tipi
**Classe CSS del link** >>Icon Icon-info (**Tutte le icons**).

### Expected result

Corretta visualizzazione delle **Icons**.

### Actual result

![cattura](https://user-images.githubusercontent.com/24791536/36110972-dd85cefa-1024-11e8-9f58-55880eed80fe.PNG)

Attualmente tutte le classi del toolkit, generano il seguente errore di visualizzazione.

![cattura1](https://user-images.githubusercontent.com/24791536/36111256-ccfdf598-1025-11e8-93c7-15f2890248f4.PNG)

### System information (as much as possible)

Joomla! 3.8.4
ItaliaPA 3.8.0.5

### Additional comments

Errata visualizzazione delle icons del Web Toolkit Styleguide.

https://italia.github.io/design-web-toolkit/components/detail/icons.html

**Comment by eshiol** [comment]
Il comportamento del template è corretto. La visualizzazione dei menu basata su icone del toolkit è possibile utilizzando il layout socials. I menu in posizione socials prendono in automatico il layout socials.

**Comment by Knock-Out** [comment]
Nel mio caso, si tratta del menu principale, posizione "main menu" con layout "megamenu" quindi, in base alla tua affermazione deduco che le icon non sono utilizzabili altrove.

**Comment by eshiol** [comment]
Al momento no. Tutto ciò che non è presente nei template del toolkit non è previsto. L'idea di aggiungere icone alle voci del megamenu mi piace.

**Comment by atodaro** [comment]
Ho provato la configurazione di una voce di menù con il ricorso a immagine png a 16px e il risultato ottenuto lo reputo soddisfacente
Esempio su [sito demo](https://paswjoomla.net/ItaliaPAsW/) megamenù "Area Alunni" -> Voce di menù "Canale Youtube".
Nella voce di menù ho inserito un'immagine di menù caricata nella cartella immagini.
![esempio link](https://user-images.githubusercontent.com/12257435/36387065-2bb70c6a-1598-11e8-8552-d9dad35a4e41.png)

**Comment by eshiol** [comment]
Nel caso di megamenu puoi provare la pr #103
