### ISSUE TITLE
Lista singola categoria - Immagine Categoria

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#101]
### Steps to reproduce the issue

Voce di menu >> Lista singola Categoria >> TAB Categoria>> **Immagine categoria - Mostra**

### Expected result

![28080329_10211224064093408_94398314_o](https://user-images.githubusercontent.com/24791536/36112278-6fba2380-1029-11e8-9368-bf6c6d15b22b.jpg)

### Actual result

La grandezza dell'immagine della categoria è impostata al 100% e la descrizione si colloca sotto l'immagine.

![28001282_10211224063813401_2055544610_n](https://user-images.githubusercontent.com/24791536/36112082-b878c578-1028-11e8-8cf7-d04a73a0d4ea.png)

### System information (as much as possible)

Joomla! 3.8.5
ItaliaPA 3.8.0.5

### Additional comments

 Come da immagine di **Expected result**, chiedo se è possibile integrare il layout **"categoria blog"**.

**Comment by eshiol** [comment]
Ti aspetti un layout di tipo news?
https://italia.github.io/design-web-toolkit/components/preview/layout--news.html

**Comment by Knock-Out** [comment]
Si, sarebbe il layout più indicato.

**Comment by atodaro** [comment]
Condivido la scelta di implementare il tipo di layout tipo news anche per la descrizione e l'immagine nelle voci di menu tipo "lista di singola categoria"

**Comment by atodaro** [comment]
@eshiol Funzionalità da predisporre per la 3.8.0.7 come new release
