### ISSUE TITLE
URL interno

### ISSUE THREAD

**Issue by salvatore26** [retepasw/joomla-italiapa#102]
### Steps to reproduce the issue
Tipo voce menu - URL interno
### Expected result
![cattura](https://user-images.githubusercontent.com/33664632/36369293-11754fc0-155b-11e8-8519-54e8649679ee.PNG)
![cattura1](https://user-images.githubusercontent.com/33664632/36369306-1a7441d0-155b-11e8-85d5-0fc68b6401da.PNG)

### Actual result

![cattura2](https://user-images.githubusercontent.com/33664632/36369316-228d8002-155b-11e8-8ee2-7998124fe5ca.PNG)
![cattura3](https://user-images.githubusercontent.com/33664632/36369326-29ef6c16-155b-11e8-9be8-b48fb3237416.PNG)

### System information (as much as possible)

Template italiaPA 3.8.0.5
Joomla 3.8.5

**Comment by atodaro** [comment]
Verificato che se creo una voce di menù del tipo "url" e punto ad un articolo si apre una pagina con le categorie: il comportamento anomalo tuttavia dipende da Joomla! e non dal template. 
Per puntare ad un articolo si deve procedere esclusivamente a linkare l'articolo scegliendo voce di menù tipo "singolo articolo".

**Comment by Knock-Out** [comment]
Perché non utilizzare

Voce di menu >> Alias voce di menu ?

**Comment by eshiol** [comment]
Se ci sono altri commenti, questa issue verrà chiusa.
