### ISSUE TITLE
New feature: pagina di login

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#108]
### Steps to reproduce the issue
Creo una voce di menù "accedi" di tipo "login" nel megamenù, formattato secondo lo stile previsto dal webtoolkit.

### Expected result
Il pulsante "accedi" mi reindirizza ad una pagina di login che consente di scegliere il tipo di login che voglio utilizzare. 
![autenticazione](https://user-images.githubusercontent.com/12257435/36551547-1aee7096-17f8-11e8-8118-9674dbbe2c18.png)

### Actual result
Funzionalità ancora non presente su Joomla: al momento, è esclusivamente possibile impostare il modulo login per la gestione dei diversi tipi di accesso.

### System information (as much as possible)
ItaliaPA 3.8.0.5
Joomla 3.8.5

**Comment by eshiol** [comment]
#476
