### ISSUE TITLE
New feature: inserimento codice Google Analytics da template

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#109]
### Steps to reproduce the issue
Da una tab del control panel di ItaliaPA ho accesso alle opzioni per l'attivazione di Google Analytics

### Expected result
Tramite il pannello di controllo di ItaliaPA inserisco il codice di tracciamento di Google Analytics, abilitando o meno google analitycs, abilito o meno l'opzione "navigazione anonima"
![google](https://user-images.githubusercontent.com/12257435/36552945-66a89e5a-17fb-11e8-9629-3bb1268f2e30.png)

### Actual result
Funzionalità non ancora implementata nella ver. 3.8.0.5

**Comment by eshiol** [comment]
Non ritengo sia corretto inserire Google Analytics nel template. Il template dovrebbe gestire solo la veste grafica del sito, funzionalità aggiuntive dovrebbero essere gestite via plugin.
