### ISSUE TITLE
Modulo Menu - layout Treeview - Icon 

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#111]
### Steps to reproduce the issue

Ho creato un modulo **tipo Menu** (collegandolo al menu predisposto) in posizione right , con **Suffisso classe menu**  "treeview--plus" e layout treeview o  Treeview-1 o Treeview-1.
Nella voce di menu ho inserito in **Opzione link** la Classe CSS del link **Icon-list**.

### Expected result

Le icone sono visualizzate in modo anomalo. Mi aspetto il medesimo risultato del mega-menu.

#100  #103 

### Actual result

Errata visualizzazione delle icons del Web Toolkit Styleguide.

![cattura](https://user-images.githubusercontent.com/24791536/36583823-7c361e7e-1877-11e8-8089-403e4c7b2a38.PNG)

### System information (as much as possible)

Joomla! 3.8.4
ItaliaPA 3.8.0.5

**Comment by eshiol** [comment]
comportamento verificato
