### ISSUE TITLE
Icona voce di menù - modulo featured

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#118]
### Steps to reproduce the issue
Creo un nuovo menù e le singole voci di menù; alle voci di menù aggiungo le "Classe CSS del link" per aggiungere un'icona prevista dal toolkit; associo un modulo menù in posizione "featured".

### Expected result
Le icone e la voce di menù hanno la formattazione prevista dal toolkit e dal template.

### Actual result
La voce di menù non ha formattazione
![screenshot-paswjoomla net-2018 02 28-08-01-49](https://user-images.githubusercontent.com/12257435/36774280-ab05463c-1c5d-11e8-94e4-335e55b4d01f.png)

### System information (as much as possible)
ItaliaPA 3.8.0.6

### Additional comments

#

**Comment by eshiol** [comment]
Se aggiungi la Classe CSS del link il modulo non carica le classi di default che vanno inserite manualmente, se necessarie.
**Classe CSS del link:** `Icon-info u-textClean u-text-h3 u-color-white`

**Comment by atodaro** [comment]
Confermato il comportamento corretto con l'applicazione della classe CSS del link indicata nel commento da @eshiol

**Comment by Knock-Out** [comment]
La Classe CSS del link: `Icon-info u-textClean u-text-h3 u-color-white` è stata applicata con successo :white_check_mark: 

![cattura](https://user-images.githubusercontent.com/24791536/36786012-295758dc-1c85-11e8-8f96-87a908c86fa7.PNG)
