### ISSUE TITLE
posizioni top del template

### ISSUE THREAD

**Issue by Fra1974** [retepasw/joomla-italiapa#12]
### Steps to reproduce the issue
Il template mi visualizza due posizioni **top** con lo stesso nome nell'anteprima del template

### Expected result
inserire una immagine come header del sito, visualizzata appena sotto il mainmenu ed estesa per tutto il layout del template.

### Actual result
 Delle due posizioni top, è attiva la seconda (quella più in basso dall'anteprima) dove se inserisco una immagine la mette centrata e non estesa per tutto il layout del template.

### System information (as much as possible)
Joomla! 3.8.2
Template 3.8.0.1

**Comment by eshiol** [comment]
bug posizione top confermato. la prima posizione è cookiebar, non top.
