### ISSUE TITLE
Immagine in newsflash

### ISSUE THREAD

**Issue by alessandrooppe** [retepasw/joomla-italiapa#121]
Salve, stavo seguendo la guida su https://paswjoomla.net/ItaliaPAsW/web-toolkit-styleguide/guida-template/costruire-la-homepage?showall=&start=8, riguardante il modulo Newsflash e volevo chiedere se le news potevano avere un immagine in anteprima? e se si come?
Grazie
P.S. Complimenti per il lavoro

**Comment by atodaro** [comment]
Nella #122 ho descritto la funzionalità da implementare in riferimento al toolkit
