### ISSUE TITLE
Lista singola categoria

### ISSUE THREAD

**Issue by eshiol** [retepasw/joomla-italiapa#126]
### Steps to reproduce the issue
Creare una voce di menu lista singola categoria senza immagine

### Expected result
titolo e descrizione della categoria occupano tutta la larghezza della pagina

### Actual result
titolo e descrizione della categoria occupano metà della larghezza della pagina, come previsto quando c'è l'immagine

### System information (as much as possible)
Template ItaliaPA 3.8.0.7

### Additional comments
nel caso manchi l'immagine si dovrebbe tornare al layout previsto con Template ItaliaPA 3.8.0.6

**Comment by Knock-Out** [comment]
Preferisco la visualizzazione attuale. 
Titolo e descrizione della categoria occupano metà della larghezza della pagina, come previsto quando c'è l'immagine. #114 

![cattura1](https://user-images.githubusercontent.com/24791536/36964717-d6401892-2057-11e8-8932-87e41faa56ee.PNG)

![cattura](https://user-images.githubusercontent.com/24791536/36964715-d61b307c-2057-11e8-922d-35b714a37285.PNG)

Se dovessimo tornare indietro, non avremmo un controllo ne del testo ne dell'immagine. Qualsiasi dimensione essa sia risulterebbe sempre sproporzionata al resto del layout. Inoltre il testo della descrizione si collocherebbe al di sopra di questa rendendo la pagina non uniforme. Nel mio caso (sotto) ho inserito un immagine di grande dimensioni, se l'immagine dovesse essere di pochi pixel, il testo sarebbe esteso ma l'immagine si collocherebbe sotto . Allora non sarebbe in linea con il toolkit.

![36112082-b878c578-1028-11e8-8cf7-d04a73a0d4ea](https://user-images.githubusercontent.com/24791536/36964887-4814b8d8-2058-11e8-99e4-c3640183204e.png)

**Comment by eshiol** [comment]
la visualizzazione precedente sarebbe solo nel caso manchi l'immagine

**Comment by Knock-Out** [comment]
Quindi potresti prevedere due tipi di layout per la lista singola categoria?

**Comment by eshiol** [comment]
sempre lo steso layout, solo che occupa tutta la pagina in caso manchi l'immagine
![image](https://user-images.githubusercontent.com/12718836/36967881-37a74f48-2061-11e8-875d-b4d5387bb473.png)

**Comment by Knock-Out** [comment]
Ok, se è cosi va bene.

**Comment by ciroslitz** [comment]
Credo sia la soluzione migliore in quanto  si potrebbe presentare per alcune categorie la necessità di non avere immagine, o non averla giustificata a dx con un risultato estetico brutto. Andrebbe ridimensionato anche il carattere forse troppo grande.

**Comment by atodaro** [comment]
Condivido la soluzione "stesso layout, con testo esteso" nel caso l'immagine non sia inserita.
