### ISSUE TITLE
Problema hamburger menù

### ISSUE THREAD

**Issue by alessandrooppe** [retepasw/joomla-italiapa#128]
### Steps to reproduce the issue
Sto creando un menù in posizione mainmenu con layout megamenu

### Expected result
Mi aspetto in versione mobile di vedere il menù ad hamburger

### Actual result
![schermata 2018-03-05 alle 14 19 36](https://user-images.githubusercontent.com/28753734/36977150-796ec7a2-2080-11e8-8f10-24e323f1f940.png)

P.S. grazie ancora

**Comment by Knock-Out** [comment]
Dovresti creare un modulo tipo Menu in posizione "Menu", collegando lo stesso menù del megamenù

**Comment by alessandrooppe** [comment]
Funziona, grazie mille!
