### ISSUE TITLE
Headroom lascia spazi bianchi

### ISSUE THREAD

**Issue by alessandrooppe** [retepasw/joomla-italiapa#130]
Salve, volevo chiedere se c'era un modo per migliorare l'effetto "headroom", perché ho seguito i vari passaggi sulla guida, ma se l'articolo in evidenza ha un'immagine durante lo scrolling rimangono dei grossi spazi bianchi. 
Grazie

**Comment by atodaro** [comment]
Occorre che tu fornisca le indicazioni per riprodurre il problema, utilizzando lo schema predisposto per le issue. Senza queste indicazioni risulta difficile rispondere: io, ad esempio, con l'immagine del layout heronews, non riscontro quanto da te indicato.

**Comment by alessandrooppe** [comment]
Steps to reproduce the issue

ho seguito i vari passaggi sulla guida, ma se l'articolo in evidenza ha un'immagine durante lo scrolling rimangono dei grossi spazi bianchi.



Expected result
![schermata 2018-03-08 alle 08 35 33](https://user-images.githubusercontent.com/28753734/37242590-6d757064-246c-11e8-9dde-97735fb965c3.png)

Actual result
![schermata 2018-03-08 alle 08 35 19](https://user-images.githubusercontent.com/28753734/37242589-674eb074-246c-11e8-9d65-9652a5d7cd0c.png)

**Comment by Knock-Out** [comment]
Posso chiederti quale posizione hai assegnato al modulo breadcrumbs?

**Comment by alessandrooppe** [comment]
Non ho assegnato posizione al modulo breadcrumbs

**Comment by Knock-Out** [comment]
Potresti linkare il sito web?

**Comment by alessandrooppe** [comment]
Purtroppo è un sito non ancora online, ma lo si può notare qua http://www.comune.quarto.na.it/it/, solo che non essendoci immagini si nota molto meno

**Comment by Knock-Out** [comment]
Fin quando non sarà on line difficilmente potremmo aiutarti.
