### ISSUE TITLE
Ritorno alla home al cambio di menu

### ISSUE THREAD

**Issue by tnuukav** [retepasw/joomla-italiapa#131]
### Steps to reproduce the issue
Click su una voce del menu principale in modo da visualizzare le sottovoci.
Con il menù "espanso" si passa ad una nuova voce di menù, con un nuovo click.

### Expected result
Si dovrebbe espandere la nuova voce di menù

### Actual result
Quando si espande la seconda voce, si carica la home page (indipendentemente da quale pagina si sia) e il menù si chiude.

### System information (as much as possible)
Testato su vari siti che utilizzano ItaliaPA, da pc con mouse:
- Sul sito demo: https://paswjoomla.net/ItaliaPAsW/alunni il problema si presenta solo se si prova ad espandere, come seconda, la voce "Area Alunni".
- Sul sito http://www.liceodavincifloridia.gov.it, solo se si clicca, come seconda, la voce "Offerta Formativa" (si deve attendere un po' il sito sembra lento)
- Su altri siti (https://www.liceorummo.gov.it/ - http://www.liceotitolucreziocaro.gov.it/), invece su tutte le voci di menù.

**Comment by Knock-Out** [comment]
Devi impostare tutte le voci di menu di 1° livello come URL e inserire il  link # + alias

![cattura](https://user-images.githubusercontent.com/24791536/37483985-83326bfe-2887-11e8-8c02-0130ad1e3b8d.PNG)

**Comment by tnuukav** [comment]
Ottima soluzione, funziona perfettamente...

Grazie
