### ISSUE TITLE
Errore 500 - JHtmlIcon::edit not found - Dopo autenticazione

### ISSUE THREAD

**Issue by Fabio65** [retepasw/joomla-italiapa#136]
### Steps to reproduce the issue
Autenticazione dal modulo di login
Accesso alla home page

### Expected result
Visualizzazione home page

### Actual result

Errore 500 - JHtmlIcon::edit not found

### System information (as much as possible)
Con il debug di sistema di Joomla attivato restituisce il seguente Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/HTML/HTMLHelper.php:137
2 | Joomla\CMS\HTML\HTMLHelper::_() | JROOT/templates/italiapa/html/layouts/joomla/content/icons.php:97

### Additional comments
Il problema si verifica quando si cerca di visitare un articolo singolo dopo l'autenticazione. Non si verifica se si visita una pagina tipo categoria blog

**Comment by atodaro** [comment]
Ho riprodotto la issue su due siti ma non ho riscontrato l'errore.
Puoi indicare lo stato di sistema? Versione CMS, php, template?

**Comment by eshiol** [comment]
errore non presente
