### ISSUE TITLE
Dimensioni immagini nel modulo newsflash

### ISSUE THREAD

**Issue by alessandrooppe** [retepasw/joomla-italiapa#137]
### Steps to reproduce the issue
Ho inserito il modulo news flash, con delle news che hanno le immagini

### Expected result

Mi aspettavo le card con le immagini tutte uguali, anche se le immagini sono di dimensioni diverse

### Actual result
![schermata 2018-04-26 alle 15 26 29](https://user-images.githubusercontent.com/28753734/39308753-89fdaab6-4966-11e8-8b07-17ca2a2a68d7.png)

### System information (as much as possible)

Uso joomla 3.8.7, la prima immagine è più grande delle altre due

### Additional comments

Grazie

**Comment by eshiol** [comment]
Il template ridimensiona le immagini mantenendo la stessa larghezza. Di preciso cosa ti aspetti da due immagini con aspect ratio differenti?

**Comment by alessandrooppe** [comment]
Mi aspettavo che le ridimensionasse tutte alla stessa altezza, avendo così anche le scritte allineate

**Comment by alessandrooppe** [comment]
Ho risolto con questo override 
.item-image img{
	height: 250px;
}
