### ISSUE TITLE
Assegnazione moduli

### ISSUE THREAD

**Issue by alessandrooppe** [retepasw/joomla-italiapa#138]
### Steps to reproduce the issue
Salve, il mio problema è il seguente:
ho creato l'homepage con caroseul, newsflash e i menu i  posizione service e featured. Si vedono, ma si vendono anche nelle pagine seguenti(es. se seguo il link nel leggi tutto nel modulo newsflash, mi fa vedere tutti i moduli nella pagina seguente) C'è un modo per evitare questo, perché assegnando solo la home nella tab "Assegnazione menù" non ha funzionato.

### Expected result
Mi aspetterei di vedere questi determinati i moduli solo nella homepage 

### Actual result

![schermata 2018-05-02 alle 16 15 03](https://user-images.githubusercontent.com/28753734/39528540-a4f86730-4e24-11e8-87f1-b5bebdbbb731.png)
![schermata 2018-05-02 alle 16 15 26](https://user-images.githubusercontent.com/28753734/39528549-a89c331c-4e24-11e8-9559-647fa0edc4bf.png)

### System information (as much as possible)
Ho seguito la guida  https://paswjoomla.net/ItaliaPAsW/web-toolkit-styleguide/guida-template/costruire-la-homepage?showall=&start=2

**Comment by eshiol** [comment]
Impostando un altro template hai il comportamento che ti aspetti oppure lo stesso che hai con ItaliaPA? Nel primo casi si tratta di un bug di ItaliaPA e va investigato oltre. Nel secondo caso si tratta del normale comportamento di Joomla.

**Comment by Knock-Out** [comment]
Verificata. Non ho riscontrato anomalie.
