### ISSUE TITLE
Lista singola categoria - descrizione categoria

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#139]
### Steps to reproduce the issue

Ho inserito la descrizione in una categoria. Ho collegato la categoria ad una voce di menu "singola categoria" e impostato l'opzione "Descrizione categoria" in Mostra.

### Expected result

Mi aspetto che la formattazione del testo `<p> </p>` sia come quella delle altre pagine.

### Actual result

![screencapture-www-sturzobiancavilla-gov-it-amministrazione-trasparente-html-1525325256067](https://user-images.githubusercontent.com/24791536/39561068-807bb176-4ea3-11e8-9062-dc4736664825.png)

### System information (as much as possible)

Joomla! 3.8.7
Italia/P> 3.8.0.7

### Additional comments

[Link del sito](https://www.sturzobiancavilla.gov.it/amministrazione-trasparente.html)

**Comment by cervinim** [comment]
Buongiorno a tutti,
sono nuovo di GitHub, spero di non aver sbagliato "area" di richiesta...
io ho lo stesso problema ma non riesco a correggerlo.
Ho verificato e non ho nessuna immagine associata.

Qualcuno può aiutarmi indicandomi i settaggi da mettere su menu/categoria ?

Grazie
