### ISSUE TITLE
Inserimento favicon

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#14]
### Steps to reproduce the issue
Richiesta new feature

### Expected result
Da control panel del template posso caricare un file da utilizzare come favicon del sito nella navigazione da front end

### Actual result
Attualmente, pur presente un file favicon all'interno della cartella "media", i browser testati: chrome, firefox ed edge non mostrano il logo nella tab della pagina web.

**Comment by eshiol** [comment]
la favicon.ico va messa nella cartella del template o nella root del sito
