### ISSUE TITLE
Componente Sitemaps

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#140]
### Steps to reproduce the issue

Ho installato un componente esterno, OSMap Free: Sitemaps. Ho creato una nuova voce di menu e ho collegato il componente. 

### Expected result

Mi aspetto che la formattazione della sitemaps sia in linea con il web toolkit. Si tratta di una lista di link quindi credo che la formattazione corretta sia [Linklist: Default](https://italia.github.io/design-web-toolkit/components/detail/linklist--default.html)

### Actual result

![screencapture-www-sturzobiancavilla-gov-it-sitemaps-html-1525325882986](https://user-images.githubusercontent.com/24791536/39561271-f1260736-4ea4-11e8-8dc5-7a4eb05c1c87.png)

### System information (as much as possible)

Joomla! 3.8.7
Italia/P> 3.8.0.7

### Additional comments
[Link del sito](https://www.sturzobiancavilla.gov.it/sitemaps.html)

**Comment by jeckodevelopment** [comment]
Ciò significa che ti aspetti un override degli stili predefiniti del componente per sitemap da parte del template.
Il problema è che potrebbero essere utilizzati diversi componenti per sitemap e bisognerebbe stilizzarli tutti o effettuare una scelta ben precisa.

**Comment by eshiol** [comment]
#260
