### ISSUE TITLE
Pulsante "invio email" diverso dalla template d'esempio

### ISSUE THREAD

**Issue by FaccioF** [retepasw/joomla-italiapa#142]
### Steps to reproduce the issue
-Installazione Template Joomla vuoto
-Creazione di un contatto mail

### Expected result
Pulsante di invio email riquadrato e di colore blu.

### Actual result
Aprendo il contatto per inviare una mail, non trovo il pulsante di invio mail come si presentava nella template d'esempio, ma è presente solo la scritta "invio email". La scritta è funzionante.

**Comment by eshiol** [comment]
Anomalia non confermata.
