### ISSUE TITLE
Editor Tiny - Buttons Immagine

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#143]
### Steps to reproduce the issue

Creo un articolo lato frontend, nell'editor Tiny, esattamente il button Immagine, il layout non ha una formattazione.

### Expected result

Mi aspetto un layout come quello del backend

![cattura1](https://user-images.githubusercontent.com/24791536/41392554-ab4d5818-6fa1-11e8-8c6a-96784c673ee6.JPG)

### Actual result

![cattura](https://user-images.githubusercontent.com/24791536/41392549-9ecabdba-6fa1-11e8-94e8-692ce54f800c.JPG)

### System information (as much as possible)

Joomla 3.8.8
Italia/P> 3.8.0.7

**Comment by eshiol** [comment]
Per semplificare lo sviluppo del template si è scelto di non basare il layout component su it WebToolkit, ma di usare un layout basato su bootstrap 3. #193
