### ISSUE TITLE
Richiesta di implementazione "Articoli in evidenza di tutte le categorie con layout News".

### ISSUE THREAD

**Issue by Rhiannon81** [retepasw/joomla-italiapa#149]
Salve Vorrei utilizzare gli "Articoli in evidenza di tutte le categorie con layout News" al posto di "Articoli in evidenza di tutte le categorie (layout: Hero News)".
Per adesso sto utilizzando come "Categoria blog (layout: News)" ma appeno clicco leggi tutto non funziona o mi apre la pagina di home con articolo esteso.
Se è possibile spiegare come implementarlo.
Grazie.

**Comment by Knock-Out** [comment]
Verificata. Non ho riscontrato anomalie.
