### ISSUE TITLE
Menu utenti login

### ISSUE THREAD

**Issue by salvatore26** [retepasw/joomla-italiapa#15]
### Steps to reproduce the issue

Redirezione voce di menù login

### Expected result

Reindirizzamento alla voce di menu scelta

### Actual result

Reindirizza sempre a: /accedi/profile

### System information (as much as possible)

joomla 3.8.2
template 3.8.0.1

**Comment by eshiol** [comment]
Comportamento confermato. Dopo il login l'utente non viene reindirizzato alla pagina impostata nell'opzione Redirezione voce di menu login
