### ISSUE TITLE
Nuove posizini nel template zongh

### ISSUE THREAD

**Issue by Iomedesimo** [retepasw/joomla-italiapa#150]
Buongiorno.
Sono un docente che stà utilizzando il template zongh gentilmente elaborato da porte aperte sul web per il mio istituto scolastico.
Sto cercando di inserire nuove posizioni nel template.
In quale file posso trovare le dichirazioni <jdoc:include type="modules" ..... per poter definire le nuove posizioni?
Ringraziandovi per il vostro prezioso lavoro, porgo i miei più cordiali saluti.

**Comment by atodaro** [comment]
Richiesta non pertinente all'argomento. Per il template "Zhong" rivolgersi allo sviluppatore del template
