### ISSUE TITLE
Errore visualizzazione menu principale se si effettua login da frontend

### ISSUE THREAD

**Issue by webmastro** [retepasw/joomla-italiapa#160]
### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/45921836/50057959-1911b080-0172-11e9-87d2-42d1411043ed.png)

### Expected result
![image](https://user-images.githubusercontent.com/45921836/50057962-2b8bea00-0172-11e9-9b9a-3a3046feccac.png)

### Actual result
![image](https://user-images.githubusercontent.com/45921836/50057968-3f375080-0172-11e9-81fe-48996cdf7388.png)

### System information (as much as possible)
Joomla 3.9.1

### Additional comments
Il megamenu sparisce se effettuo login

**Comment by eshiol** [comment]
Errore non confermato. Se non verranno forniti ulteriori dettagli su come riprodurre l'errore la issue sarà chiusa.
