### ISSUE TITLE
Lista di tutte le categorie - errore visualizzazione megamenu

### ISSUE THREAD

**Issue by webmastro** [retepasw/joomla-italiapa#161]
### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/45921836/50058006-ae14a980-0172-11e9-9f37-f228c0346d1f.png)

### Expected result
![image](https://user-images.githubusercontent.com/45921836/50058090-d224ba80-0173-11e9-8722-89000110c5e4.png)

### Actual result
![image](https://user-images.githubusercontent.com/45921836/50058111-347dbb00-0174-11e9-805e-92ced0f61d97.png)

### System information (as much as possible)
Joomla 3.9.1

### Additional comments
Il megamenu non compare se la pagina visitata è del tipo "Articoli->Lista di tutte le categorie"

**Comment by eshiol** [comment]
Errore non confermato. Se non verranno forniti ulteriori dettagli su come riprodurre l'errore la issue sarà chiusa.
