### ISSUE TITLE
megamenu molto popolato alcune voci di menu non sono visibili

### ISSUE THREAD

**Issue by vittorioalfieri** [retepasw/joomla-italiapa#167]
### Steps to reproduce the issue
Aggiungere su una voce di menu più di 5 submenu con ognuna almeno 10 voci.
Con alcune risoluzioni il megamenu non scorre con la pagina ed alcune voci dei sottomenu non sono visibili.
Risoluzione schermo: 1366x768

### Expected result
![megamenu-open](https://user-images.githubusercontent.com/18733784/53300159-ac86f200-3843-11e9-94f0-f2a067bc2682.png)

### Actual result
[Megamenu-2019-02-24T13-38-05-701Z.zip](https://github.com/retepasw/joomla-italiapa/files/2897937/Megamenu-2019-02-24T13-38-05-701Z.zip)

### System information (as much as possible)
Joomla 3.9.3

**Comment by eshiol** [comment]
Bug confermato.
### System information (as much as possible)
Template ItaliaPA 3.8.0.8
Headroom: Sì
