### ISSUE TITLE
Elenchi puntati ed elenchi numerati

### ISSUE THREAD

**Issue by juppy72** [retepasw/joomla-italiapa#220]
### Steps to reproduce the issue
Salve, da quando ho istallato la quickstart di Italiapass, l'editor Tiny, versione personalizzata italiapassw non mi permette di fare gli elenchi puntati e numerati. Sapete spiegarmi perché? Esiste il pulsante, ma non agisce nulla.
O meglio da codice html risultano applicati ma nell'editor visuale non spuntano. Qualcuno sa perché?

**Comment by eshiol** [comment]
#223
