### ISSUE TITLE
Colore Titolo articoli layout "Articoli in evidenza di tutte le categorie"

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#224]
### Steps to reproduce the issue
Assegnare alla voce di menù "Home" il layout "Articoli in evidenza di tutte le categorie"
Settare la voce di menù con 4 articoli principali, 4 articoli introduttivi, 4 colonne e 2 link.
Creare diversi articoli in evidenza ad accesso "registered" 

### Expected result
Il titolo degli articoli introduttivi per "registered" ha la stessa formattazione degli articoli per "public" 

### Actual result
Il titolo degli articoli per "registered" nelle colonne degli articoli introdutti ha un colore grigio senza adeguato contrasto con lo sfondo del modulo a quattro colonne.

### System information (as much as possible)
Joomla 3.9.11
ItaliPA: 3.8.0.13 con tema Italia; il problema si manifesta anche con gli altri temi
![Screen Homepage](https://user-images.githubusercontent.com/12257435/65302729-4d405480-db7c-11e9-9d39-65e53e18a076.png)

### Additional comments
Url sito test: https://test.icverdellino.edu.it

**Comment by eshiol** [comment]
issue confermata
