### ISSUE TITLE
Immagine estesa articolo layout single article

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#23]
### Steps to reproduce the issue
Creo un nuovo articolo e inserisco un'immagine per la visualizzazione estesa
### Expected result
L'immagine estesa del placeholder, a prescindere dalla sua risoluzione nativa, si ridimensiona in funzione della risoluzione del device utilizzato per navigare nel sito.

### Actual result
L'immagine del placeholder non si ridimensiona.

### System information (as much as possible)
Joomla 3.8.1
Template 3.8.0.1

**Comment by eshiol** [comment]
Comportamento confermato
