### ISSUE TITLE
Menu dx in position8

### ISSUE THREAD

**Issue by gpasc** [retepasw/joomla-italiapa#236]
Ho provato a configurare un menu_dx in position8.
Non si visualizza perchè position8 non appartiene a ItaliaPASW.
Provando a scegliere posizione right, il menu' viene visualizzato a dx, ma nell'intestazione.

Sarebbe possibile posizionare un menu' in position8, ossia a dx dell'area News?
Grazie

**Comment by eshiol** [comment]
La posizione indicata non è prevista dal template.
