### ISSUE TITLE
[RFC] Inserimento Custom code before </head>: plugin o template?

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#244]
### Steps to reproduce the issue
Pubblico un articolo su sito realizzato con ItaliaPA e lo condivido su Facebook o altri social

### Expected result
L'anteprima del post su facebook riporta un'immagine con il logo del sito

### Actual result
L'anteprima non riporta immagini o prende casualmente immagini della pagina

### Additional comments
É il caso di inserire nel pannello di controllo del template una finestra per l'inserimento di Custom code before </head> o è preferibile individuare/creare un plugin specifico?

**Comment by eshiol** [comment]
Se lo pubblichi con il template di default Protostar hai un comportamento differente?

**Comment by eshiol** [comment]
Compito del template è definire la modalità di presentare le informazioni. L'aggiunta dei tag Open Graph deve avvenire tramite plugin.

**Comment by atodaro** [comment]
Sto testando un plugin di terze parti per l'aggiunta di queste funzionalità.

**Comment by Knock-Out** [comment]
> Compito del template è definire la modalità di presentare le informazioni. L'aggiunta dei tag Open Graph deve avvenire tramite plugin.

Ho testato il plugin [Phoca Open Graph Plugin](https://www.phoca.cz/download/category/62-phoca-open-graph-plugin) con ottimi risultati. [Documentazione](https://www.phoca.cz/documentation/category/90-phoca-plugins).

![Cattura](https://user-images.githubusercontent.com/24791536/101627151-335b8d80-3a1e-11eb-8bc0-f7c218f3f5ac.JPG)

**Comment by eshiol** [comment]
Si suggerisce l'uso di un plugin open graph
