### ISSUE TITLE
Icone non visibili in menu layout linklist: rif. PR #245

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#247]
### Steps to reproduce the issue
Creo un menu
Collego il menu a un modulo con layout "linklist" in posizione "services"
Attribuisco alle voci di menu i codici icone nel campo "Classe Immagine" della tab "Opzioni Link"

### Expected result
Il testo delle voci di menu è preceduto dalle icone

### Actual result
Le icone non sono visibili

### System information (as much as possible)
Joomla 3.9.13
ItaliaPA 3.8.0.14

### Additional comments
Issue riferita alla PR https://github.com/retepasw/joomla-italiapa/pull/245

**Comment by eshiol** [comment]
Corretta con la 3.8.0.15
