### ISSUE TITLE
Titolo modulo Elenco Categorie

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#249]
### Steps to reproduce the issue
Creo un modulo di tipo "Elenco Categorie" in posizione featured; seleziono "Mostra titolo" dalla tab "Modulo" per visualizzare il titolo del modulo

### Expected result
In frontend visualizzo il titolo del modulo sopra le tiles delle singole categorie.

### Actual result
Il titolo del modulo non è visibile

### System information (as much as possible)
Test effettuato su template ver. 3.8.0.14

### Additional comments
Comportamento confermato anche su sito demo italiapasw
https://paswjoomla.net/ItaliaPAsW/index.php?option=com_content&view=category&id=62&Itemid=173

**Comment by eshiol** [comment]
al momento (3.8.0.15) la posizione featured non ha la possibilità di visualizzare il titolo

**Comment by eshiol** [comment]
Di default i moduli in posizione featured non hanno titolo. Utilizzare un altro stile modulo.
