### ISSUE TITLE
Plugin Content Vote

### ISSUE THREAD

**Issue by danimara** [retepasw/joomla-italiapa#250]
### Steps to reproduce the issue
Clicco sulle stelline per votare

### Expected result
Vorrei vedere messaggio di successo e votazione

### Actual result
Nessun risultato nel browser. 
Analizzando la console degli errori: 
ReferenceError: Joomla is not defined prenotazione-dei-servizi-online:1:1
    onchange https://www.comune.udine.it/servizi/servizi-online/prenotazione-dei-servizi-online:1

Debugger: 
Joomla.submitform('article.vote', document.getElementById('voteForm'), false);

### System information (as much as possible)
Joomla 3.9.13
Template ItaliaPA 3.8 Alpha14

### Additional comments
Ho provato sul sito https://www.eshiol.it/it/template-italiapa/ipa/plugin/content-vote.html e il plugin funziona.
Ho testato in locale una nuova versione di Joomla e il template ItaliaPA 3.8 Alpha 14 e nemmeno lì funziona.
Se disabilito l'override del plugin di ItaliaPA il sistema di votazione funziona
![2019-11-20 13_38_19-Carta famiglia  Comunicazione di avvio del procedimento - Clone Comune Udine - O](https://user-images.githubusercontent.com/4980244/69239683-15b15100-0b9b-11ea-81e4-c006a68fd46f.png)

![2019-11-20 13_32_20-Prenotazione dei servizi online - Comune Udine](https://user-images.githubusercontent.com/4980244/69239340-45138e00-0b9a-11ea-9fe5-b7bb5a824bde.png)
![2019-11-20 13_32_42-Prenotazione dei servizi online - Comune Udine](https://user-images.githubusercontent.com/4980244/69239341-45138e00-0b9a-11ea-8dbc-3aa672aa914d.png)

**Comment by eshiol** [comment]
E' motivo di orgoglio appurare che un Comune prestigioso come quello di Udine abbia deciso di utilizzare il template ItaliaPA. Così come lascia interdetti constatare che sul sito non sia presente alcun riferimento a Helios Ciancio a eshiol.it e a PAsW e siano stati rimossi i link a fondo pagina. La rimozione dei riferimenti a chi si è prodigato per la realizzazione del progetto ItaliaPA denota una scarsa sensibilità e rispetto nei confronti del lavoro altrui e della cultura Open Source.

Per il problema in questione provi ad aggiungere alla riga 19 del file templates/italiapa/html/plg_content_vote/vote.php il seguente codice:

`JHtml::_('behavior.core');`

**Comment by danimara** [comment]
Buongiorno,
grazie per la risposta.
Per i riferimenti agli sviluppatori chiedo scusa, era stata chiesta una modifica in fase di test che non è stata ripristinata quando siamo andati online: grazie per la segnalazione, ora è nuovamente visibile.

**Comment by eshiol** [comment]
Corretta con la 3.8.0.15
