### ISSUE TITLE
I titoli di menu non dovrebbero essere di tipo URL

### ISSUE THREAD

**Issue by jeckodevelopment** [retepasw/joomla-italiapa#251]
Nella guida per costruire l'home page utilizzando il template ItaliaPA, è suggerito l'utilizzo di voci di menu di tipo `URL` con destinazione `#` per i titoli dei menu. 
https://paswjoomla.net/ItaliaPAsW/index.php?option=com_content&view=article&id=2472:la-costruzione-della-homepage-con-italiapa&catid=379&limitstart=4&Itemid=1063

![immagine](https://user-images.githubusercontent.com/733133/69912671-eddcab80-142c-11ea-8d81-b85b52c102e3.png)

Sarebbe più corretto, tecnicamente, utilizzare voci di menu del tipo "**Separatore testuale**".
Il risultato grafico è identico, ma non ci sarebbero link a "#".

**Comment by eshiol** [comment]
Concordo. Documentazione aggiornata.
