### ISSUE TITLE
Errori di visualizzazione Icone Social Versione 3.8.0.14

### ISSUE THREAD

**Issue by antoprd** [retepasw/joomla-italiapa#252]
### Steps to reproduce the issue
Inserire un menu social seguendo lo schema della guida

### Expected result
Visualizzazione dell'Icona social corrispondente

### Actual result
Visualizzazione di una scritta errata

### Additional comments

![image](https://user-images.githubusercontent.com/53812256/70395974-a0e86e80-1a04-11ea-9c2e-5e9dffe8c2a5.png)

**Comment by antoprd** [comment]
La stessa procedura con la Versione 0.6, 0.7 e 0.8 funziona normalmente. L'errore si produce dalla versione 0.9

**Comment by eshiol** [comment]
A partire dalla alpha 9 la gestione delle icone menu è cambiata.
https://www.eshiol.it/it/template-italiapa/guide/menu/icone.html
Ti consiglio di dare una veloce lettura alle pagine di rilascio del template a partire dalla alpha 9
https://www.eshiol.it/it/template-italiapa/news-italiapa/263-rilasciato-template-italiapa-3-8-alpha-9.html
