### ISSUE TITLE
Pulsanti di navigazione articoli e Moduli

### ISSUE THREAD

**Issue by antoprd** [retepasw/joomla-italiapa#254]
Salve, mi chiedevo se esista un'opzione per rimuovere i pulsanti di navigazione in alcuni articoli. 
Mi riferisco alle frecce laterali e quelle che puntano verso il basso che si trovano in fondo ad un articolo e in cima ad una nuova sezione della pagina (Allego immagine).
Non vorrei toglierli dal codice perché non voglio eliminarli da tutti gli articoli, solo nasconderli in alcune parti del sito.
Grazie.

![image](https://user-images.githubusercontent.com/53812256/71913023-dc4a9a00-3176-11ea-96b2-0552ae7b1ca4.png)

**Comment by eshiol** [comment]
Al momento no. Sarà aggiunta l'opzione nella alpha 15.
