### ISSUE TITLE
Pagina di errori non usa css personalizzato

### ISSUE THREAD

**Issue by cervinim** [retepasw/joomla-italiapa#255]
Buongiorno a tutti,
come da titolo, la pagina error.php (oltre a non mostrare correttamente il logo), non utilizza il file css personalizzato user.css .
E' già capitato a qualcuno? Sapete aiutarmi?

Grazie.

p.s.: il sito in questione è [https://www.ats-insubria.it](url)

**Comment by eshiol** [comment]
La pagina di errore ha qualche problemino, tra cui sembra ci sia anche il mancato caricamento del file user.css.

**Comment by eshiol** [comment]
Corretta con la 3.8.0.15

**Comment by cervinim** [comment]
Ciao, nonostante l'aggiornamento alla 3.8.0.15, sul mio sito non viene ancora caricato il css personalizzato.
Grazie e ciao.
