### ISSUE TITLE
RFC: questa pagina ti è stata utile?

### ISSUE THREAD

**Issue by eshiol** [retepasw/joomla-italiapa#259]
RFC: realizzazione pulsante questa pagina ti è stata utile?
![Annotazione 2020-01-22 171634](https://user-images.githubusercontent.com/12718836/72929337-ef09c500-3d59-11ea-8be5-4da0867791e5.png)

**Comment by atodaro** [comment]
Ho visto sul sito eshiol.it la funzionalità introdotta e sarebbe importante averla a disposizione nel template, anche attraverso un override del componente per la votazione degli articoli.

**Comment by eshiol** [comment]
Aggiunto il supporto al plugin Content - Vote for ItaliaPA, in attesa del rilascio ufficiale.
#333

**Comment by eshiol** [comment]
Completato il rilascio del plugin Content - Vote for ItaliaPA.
