### ISSUE TITLE
errata formattazione elenchi puntati e numerati

### ISSUE THREAD

**Issue by juppy72** [retepasw/joomla-italiapa#268]
### Steps to reproduce the issue
Salve ancora ad oggi nonostante tutto non riesco a rendere visibili gli elenchi puntati o numerati 
![elenchi-puntati](https://user-images.githubusercontent.com/55456178/73119791-3fa23d80-3f67-11ea-80a2-3eda7606aaed.png)
nel mio editor Joomla preinstallato nel template Italiapassw.
Ovvero il codice html mi dice che ci sono ma se vado nell'editor visuale questi non spuntano. Che fare? Sta diventando davvero problematico qualcuno potrebbe aiutarmi?

**Comment by vittorioalfieri** [comment]
Scusa ma postresti essere più preciso ?
che versione di template usi ?
che editor usi ? JCE o TinyMCE?
il difetto è solo in fase di editing o anche visualizzando la pagina nel frontend ?

**Comment by juppy72** [comment]
Gentilissimi, grazie di esservi fatti sentire. In realtà oggi mi accorgo che si è misteriosamente sistemato tutto da solo. Dopo l’aggiornamento all’ultima versione di Italia Pass non era cambiato nulla, ma solo oggi mi accorgo che spuntano in frontend e nell’editor visuale TinyMCE sia gli elenchi puntati che gli elenchi numerati.
Prima questi risultavano in html ma non in visuale. Adesso, ripeto, si è misteriosamente sistemato tutto. Misteri dell’informatica.

Cordialità.
Giuseppe Cammarata.
