### ISSUE TITLE
Slider Articoli in evidenza di tutte le categorie (layout: Hero news)

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#274]
### Steps to reproduce the issue

Creo 1 voce di menu » Articoli in evidenza di tutte le categorie (layout: Hero news)
Tipo di voce di menu *Articoli in evidenza di tutte le categorie.

Creo 2 articoli in evidenza con immagine d'introduzione.

### Expected result

![slide_1](https://user-images.githubusercontent.com/24791536/73475845-775b1c00-4391-11ea-8c7d-7f97a765ef23.jpg)

![slide_2](https://user-images.githubusercontent.com/24791536/73476080-e5074800-4391-11ea-9dac-9e2f0ab9a677.jpg)

### Actual result

Home page: è presente solo 1 articolo In evidenza con immagine d'introduzione.
Attualmente non è possibile scorrere gli articoli.

![slide_no](https://user-images.githubusercontent.com/24791536/73475801-58f52080-4391-11ea-9eb4-4be6c22aa881.jpg)

### Additional comments
Voce di menu >> Articoli » Categoria blog.

![Circolari e comunicazioni](https://user-images.githubusercontent.com/24791536/73476644-ee44e480-4392-11ea-8c66-66ffc06b8881.png)

**Comment by eshiol** [comment]
Confermo che il layout: Hero news visualizza un solo articolo, così come previsto del web toolkit.

**Comment by eshiol** [comment]
Carousel di articoli principali con layout Hero news, articoli introduttivi e link con layout simile a categoria blog.

**Comment by atodaro** [comment]
Verificare la possibilità che l'immagine del layout Hero news sia quella estesa e non l'introduttiva.
Motivo: l'introduttiva utilizzata nei newsflash ha generalmente risoluzione inferiore e in hero la resa visiva sarebbe pessima; di contro, immagini a risoluzione troppo elevata rischiano di diminuire la velocità di caricamento della homepage.

**Comment by eshiol** [comment]
Come spesso accade c'è la teoria e la pratica.
La teoria:
Immagine introduzione - Immagine per il testo introduttivo, per gli articoli visualizzati in stile blog e gli articoli in evidenza
Immagine articolo esteso - Seleziona o carica un'immagine per la visualizzazione del singolo articolo
La pratica:
Immagine introduzione - immagine piccola
Immagine articolo esteso - immagine grande

La tua riflessione è corretta e merita un approfondimento. Nessuna delle due immagini nasce per lo scopo, la soluzione migliore sarebbe aggiungere un campo personalizzato
**Immagine Hero news** - Seleziona o carica un'immagine per gli articoli visualizzati in stile articoli in evidenza layout Hero News
In questo modo non viene stravolto il comportamento atteso e rimangono utilizzabili le due immagini di default per gli scopi per cui sono state pensate.

**Comment by atodaro** [comment]
Condivido la tua proposta, nell'ottica del rispetto della filosofia progettuale del Cms

**Comment by eshiol** [comment]
PR #358
