### ISSUE TITLE
Privacy » Conferma richiesta: Proprietà non definita

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#280]
### Steps to reproduce the issue

Creo 1 voce di menu » Privacy » Conferma richiesta

### Expected result

![I am a Webmaster - Claudio Rosselli - conferma richiesta](https://user-images.githubusercontent.com/24791536/73564073-1ef25000-445f-11ea-8163-a27b92198c6d.png)

### Actual result

**Avviso: Proprietà non definita**

![Conferma richiesta](https://user-images.githubusercontent.com/24791536/73564089-26b1f480-445f-11ea-8113-bb6296cc1e26.png)

### System information (as much as possible)

Joomla! 3.9.15
ItaliaPA 3.8.0.15

### Additional comments

**Crea richiesta**

![Crea richiesta](https://user-images.githubusercontent.com/24791536/73563944-d63a9700-445e-11ea-929a-cda715bec147.png)

**Estendi consenso**

![Estendi consenso](https://user-images.githubusercontent.com/24791536/73563986-eeaab180-445e-11ea-8f88-17363d70103f.png)

**Comment by eshiol** [comment]
errore confermato
