### ISSUE TITLE
syntax error, unexpected '<', expecting end of file

### ISSUE THREAD

**Issue by cedsupport** [retepasw/joomla-italiapa#289]
Buongiorno
installato il template ItaliaPA 3.8.0.15 ( January 2020 ) su ambiente Joomla 3.9.13 Stable(Amani) MySQL 5.7.25 PHP 7.2.14 Apache 2.4.6 per ammodernare sito Web secondo le linee guida PA viene restituito il seguente messaggio di errore :

0 syntax error, unexpected '<', expecting end of file

senza ulteriori indicazioni. Vorrei chiedere un suggerimento su come risolvere la cosa.
Ringrazio in anticipo

**Comment by Knock-Out** [comment]
Prova ad aggiornare la versione di Joomla. 
Ultima release 3.9.15

**Comment by eshiol** [comment]
Problema non confermato ed informazioni insufficienti per una analisi dello stesso.
