### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by salvatore26** [retepasw/joomla-italiapa#29]
### Steps to reproduce the issue
Assegno il modulo menù utente (visibile agli utenti registrati) alla posizione right.

### Expected result

Il modulo quando non visibile non dovrebbe occupare lo spazio consentendo al placeholder di espandersi

### Actual result

Il modulo occupa la posizione anche quando non visibile  riducendo lo spazio del placeholder non consentedogli di espandersi

### System information (as much as possible)

joomla 3.8.2
template 3.8.0.2

**Comment by eshiol** [comment]
Non è stato possibile riprodurre il comportamento anomalo. Occorrono informazioni aggiuntive: tipo voce menu e layout.
