### ISSUE TITLE
Problema Tags 

### ISSUE THREAD

**Issue by MarcelloRocca** [retepasw/joomla-italiapa#298]
### Steps to reproduce the issue
Creo un articolo da front end e seleziono in Pubblicazione i tags desiderati

### Expected result
Nella campo Tags voglio selezionare due voci Circolari Docenti e Circolari Famiglie

### Actual result
Posso attivare solo una delle due voci

### System information (as much as possible)
Joomla 3.9.15 Italiapa 3.9.0.16

**Comment by atodaro** [comment]
Con la release 3.9.0.16.1 il problema si risolve: effettuato test, si possono selezionare più tag.
Occorre attendere il rilascio ufficiale della nuova build
