### ISSUE TITLE
Aggiunta del bottone "Salva e Chiudi" in articoli frontend

### ISSUE THREAD

**Issue by NioBee** [retepasw/joomla-italiapa#299]
### Steps to reproduce the issue
Accedere al sito da frontend e creare un nuovo articolo, in basso compaiono solo i bottoni "salva" e "annulla"

Premendo il bottone "salva" l'articolo si salva chiudendosi automaticamente

Sarebbe utile avere 3 bottoni: "salva", "salva e chiudi" e "annulla", in questo modo durante la scrittura dell'articolo si potrebbe procedere ad uno o più salvataggi, senza uscire dalla modalità creazione, e solo al termine premere "salva e chiudi".

### Expected result
![image](https://user-images.githubusercontent.com/41695549/74875162-1a380200-5362-11ea-8870-4a6e6d0e667b.png)

### Actual result
![image](https://user-images.githubusercontent.com/41695549/74874938-cb8a6800-5361-11ea-89d5-d3f6a61e6e7f.png)

### System information (as much as possible)
Joomla! 3.9.15
ItaliaPA 3.9.0.16.1

**Comment by eshiol** [comment]
Al momento non è possibile. In Joomla manca il codice per gestire l'apply.
https://github.com/joomla/joomla-cms/issues/6552
