### ISSUE TITLE
Responsive categoria blog

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#30]
### Steps to reproduce the issue
Creo una voce di menù del tipo categoria blog e imposto la visualizzazione secondo i parametri indicati in figura.
![screenshot_20171118-143208](https://user-images.githubusercontent.com/12257435/32980819-ed0f81ae-cc6d-11e7-9963-79d4d979a788.png)

### Expected result
La pagina in visualizzazione mobile è perfettamente responsive e il contenuto è mantenuto all'Interno della schermata senza necessità di scrolling laterale.

### Actual result

La visualizzazione della pagina da device mobile non è del tutto responsive perché la pagina consente uno scrolling laterale pur in assenza di contenuto fuori margine
![screenshot_20171118-143929](https://user-images.githubusercontent.com/12257435/32980853-61d5fe28-cc6e-11e7-9107-537f47b0de53.png)

### System information (as much as possible)
Italiapa 3.8.0.1

**Comment by eshiol** [comment]
Il problema si presenta a prescindere dal tipo di menu/layout con headroom attivo.

**Comment by atodaro** [comment]
Confermo che effettuando altro test su [sito demo](https://antoniotodaro.it/verdellinopa/categoria-blog-test) la pagina ha comportamento non responsive. 
Effettuato altro test: disattivo il modulo "spid login" in posizione "languages" e il problema non si manifesta.
Questi comportamenti anomali si verificano esclusivamente su smartphone e non riducendo la finestra del browser e neppure utilizzando un emulatore mobile responsive.
Il modulo spid, inoltre, in fase di scrolling, sembra spostarsi verso sinistra prima della scomparsa della barra superiore. _Nel video disponibile [al seguente link ](https://drive.google.com/file/d/1Hs9S8i-ezoUGeVZ73RSQr2lYZMspaGt8/view?usp=sharing)si intravede il comportamento del modulo spid_
