### ISSUE TITLE
Condivisione email di articoli: possibile bug

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#303]
### Steps to reproduce the issue
In un articolo clicco sul pulsante "condivido" e scelgo "email; compilare il form del popup e inviare

### Expected result
L'articolo è inviato tramite email

### Actual result
L'articolo non viene inviato e il messaggio di errore nel popup riporta: "Questa email non è stata inviata."
### System information (as much as possible)
Joomla 3.9-15
ItaliaPA 3.9.0.15

**Comment by atodaro** [comment]
Ho effettuato i test sullo stesso sito con tre template diversi:
Con Zhong 4 e Protostar la mail è inviata con successo; con ItaliaPA 9.16 restituisce messaggio di errore; errore presente anche in una versione di IPa 9.15

**Comment by eshiol** [comment]
Problema confermato
