### ISSUE TITLE
Anteprima articolo riportato due volte con leggi tutto - Modulo Newflash slider 

### ISSUE THREAD

**Issue by giuoll** [retepasw/joomla-italiapa#305]
### Steps to reproduce the issue
Creo nuovo articolo impostando la categoria su news.
Oltre che nel modulo newflash viene mostrato anche nello slider.

### Expected result
Che venga mostrato come da articolo.
Introduzione e leggi tutto.

### Actual result
Viene riportato due volte l'introduzione dell'articolo
[
![Screenshot (1)](https://user-images.githubusercontent.com/59873089/75330965-3c5de280-5882-11ea-85f7-16339025e470.png)
](url)
### System information (as much as possible)

ItaliaPA 3.0.9.16 Nightly Builds

### Additional comments
Se clicco sul leggi tutto viene tolta la parte dell'articolo presente prima del leggi tutto

![Screenshot (2)](https://user-images.githubusercontent.com/59873089/75331785-9ad79080-5883-11ea-93f0-38aab9f743bd.png)

**Comment by eshiol** [comment]
PR #296
