### ISSUE TITLE
Dimensione del logo zona Footer non specificata nel CSS

### ISSUE THREAD

**Issue by vittorioalfieri** [retepasw/joomla-italiapa#306]
### Steps to reproduce the issue
Ho sostituito il file di logo usando un file di tipo SVG e mentre il logo della Header viene visualizzato correttamente, il logo nella zona Footer viene visualizzato gigantesco.
Analizzato il CSS applicato all'elemento noto che non è prevista formattazione per il logo nella zona Footer.
è possibile provare la pagina su: https://test.iismarconipieralisi.it

### Expected result
![pagina_corretta](https://user-images.githubusercontent.com/18733784/75483602-7ecd0f80-59a7-11ea-8ce7-1ccf81e2b301.png)

### Actual result
![pagina_errata](https://user-images.githubusercontent.com/18733784/75483588-78d72e80-59a7-11ea-8f81-93b751b412ca.png)

### System information (as much as possible)
Joomla 3.9.19
PHP 7.2
ItaliaPA 3.9.0.16

**Comment by vittorioalfieri** [comment]
Inserendo queste direttive CSS nel mio foglio di stile personalizzato (user.css) ho temporaneamente risolto il problema, ma forse andrebbero implementate anche nella release ufficiale ma non so se siano corrette in tutti i casi.

`.Footer-logo 
{
  height: 4.5rem;
}
@media screen and (min-width: 768px) and (max-width: 991px), screen and (min-width: 992px) and (max-width: 1365px), screen and (min-width: 1366px) {
  .Footer-logo 
  {
    height: 6.4rem;
  }
}`

**Comment by atodaro** [comment]
Il consiglioi è quello di ridurre le dimensioni del logo: 78x78 o 100x100 px, evitando in questi casi il ricorso a fogli di stili personalizzati.

**Comment by vittorioalfieri** [comment]
il file SVG in questione è grande 75x75 ma essendo un formato vettoriale questo viene adattato coprendo tutto lo spazio possibile.
Ho aperto apposta una richiesta per poter correggere il foglio stile del tema.

**Comment by eshiol** [comment]
Inserendo adesso la personalizzazione dello stile del logo nel footer si rischia un risultato indesiderato nei siti già esistenti. L'indicazione è quella di usare il foglio di stile personalizzato come suggerito da @vittorioalfieri .
