### ISSUE TITLE
Errore in fase inserimento articolo da frontend

### ISSUE THREAD

**Issue by cervinim** [retepasw/joomla-italiapa#308]
### Steps to reproduce the issue
Upgrade del template da 3.8.0.15.6 a 3.9.0.16

### Expected result
Normale funzionamento dell'inserimento/modifica articolo da frontend

### Actual result
In fase di inserimento articolo da frontend non visualizza la prima categoria abilitata mentre seleziona automaticamente il primo tag; se vado a modificare un articolo già esistente associato alla prima categoria abilitata, ritorna errore di "categoria non inserita"

### System information (as much as possible)
Joomla! 3.9.15

**Comment by eshiol** [comment]
Anomalia confermata e risolta con la PR #297
