### ISSUE TITLE
Immagine articolo in evidenza non visibile in sito multilingua

### ISSUE THREAD

**Issue by gianlucakovarich** [retepasw/joomla-italiapa#309]
### Steps to reproduce the issue

Buongiorno! Condivido qui il post aperto sul Forum di Joomla a questo indirizzo:
https://forum.joomla.it/index.php/topic,271721.0.html

Dopo aver attivato il multilingua, non viene visualizzata l'immagine dell'articolo in evidenza in homepage, per il fatto che viene cercata nel cercata nel percorso "it/images/..." o "en/images/...", che ovviamente non esiste.

Potete vedere questo inconveniente a questo link:
http://www.autoritadibacino.sviluppo.host/en/

Nella versione italiana, l'immagine viene visualizzata impostando nel plugin Systeme - Language filter l'opzione "Rimuovi il prefisso dalla lingua predefinita" su SI.

Nella versione inglese, invece, l'immagine (cercata all'indirizzo "en/images/..." non viene visualizzata.

E' un "bug" risolvibile?

Ringrazio in anticipo per l'attenzione :)

**Comment by Knock-Out** [comment]
Hai creato 3 menu con 3 voci di menu Home >> Articoli in evidenza di tutte le categorie?

1. Home >> Lingua Tutte
2. Home IT >> Lingua IT
3. Home EN >> Lingua EN

Hai creato due articoli?

1. Articolo in Evidenza IT
2. Articolo in evidenza EN

In articolo in evidenza EN hai assegnato l'immagine?

**Comment by gianlucakovarich** [comment]
Si esatto.

Il percorso dell'immagine è questo: "images/lago-maggiore-1920x600.jpg"

Se non rimuovo il prefisso dalla lingua predefinita (lasciando, quindi, NO l'opzione del plugin Language Filter) anche nella versione italiana scompare l'immagine, perchè viene cercata all'indirizzo "it/images/lago-maggiore-1920x600.jpg".

Come presumo, "it/" e "en/" vengono anteposti automaticamente al percorso dell'immagine.

**Comment by Knock-Out** [comment]
Potrebbe trattarsi di un impostazione SEO.

Prova a settare NO riscrivi URL SEF e suffisso URL

![Configurazione globale - Scuola Svizzera Catania - Amministrazione](https://user-images.githubusercontent.com/24791536/76206280-00b90600-61fc-11ea-9f85-c43c25353ecd.png)

**Comment by gianlucakovarich** [comment]
Niente da fare:
http://www.autoritadibacino.sviluppo.host/index.php/en/

L'immagine viene cercata all'indirizzo: "index.php/en/images/..."

Le impostazioni SEO sono:
Attiva URL SEF: SI
Riscrivi URL SEF: NO
Suffisso URL: NO
Alias Unicode: NO

**Comment by Knock-Out** [comment]
Hai associato i menu e gli articoli?
Prova a disattivare tutte le opzioni SEO.

Svuota la cache.

**Comment by gianlucakovarich** [comment]
Ti confermo, come puoi vedere, che impostando Attiva URL SEF a NO, l'immagine viene visualizzata correttamente in entrambe le lingue.

**Comment by Knock-Out** [comment]
Quindi è un problema dell'impostazione del sito multilingua.
Ti consiglio di rivedere la configurazione.

https://docs.joomla.org/J3.x:Setup_a_Multilingual_Site/it

Ps. Hai duplicato il template?

https://docs.joomla.org/J3.x:Setup_a_Multilingual_Site/Duplicate_your_Template

E infine, prima di attivare Riscrivi URL modifica il file htaccess.txt, aggiungi l'hashtag

`# Options +FollowSymlinks`

Salva e modifca l'estensione in .htaccess

**Comment by gianlucakovarich** [comment]
Domanda:; è necessario duplicare il template se non ho necessità di personalizzare in modo diverso i siti nelle varie lingue? Te lo chiedo perchè non è il primo sito multilingua che realizzo e non ho mai avuto la necessità di duplicare il template.

E il problema del percorso dell'immagine è la prima volta che mi si presenta - è la prima volta che imposto un sito multilingua con il template ItaliaPA.

Comunque, siamo proprio sicuri che non sia un "bug" del template?
