### ISSUE TITLE
Errore pagina bianca aprendo modifica allegati attachments

### ISSUE THREAD

**Issue by giuoll** [retepasw/joomla-italiapa#310]
### Steps to reproduce the issue
Clicco sul pulsante modifica degli allegati di un articolo

### Expected result
Che si apra la finestra di modifica per variare l'accesso al documento ( es. da public a registred)

### Actual result

Ogni tanto la finestra di modifica si apre a piena pagina e quando si salva la variazione rimane una pagina bianca e devo ricaricare il backend

### System information (as much as possible)

ItaliaPA 3.0.9.16 Nightly Builds
PHP 7.0

**Comment by eshiol** [comment]
Non sembra un problema del template. Ti consiglio di verificare con il template di default di Joomla.

**Comment by Knock-Out** [comment]
**Front-end** - Errore confermato. Il tasto Update genera una pagina bianca. Il tasto Cancel non torna indietro.

![Quickstart ItaliaPA](https://user-images.githubusercontent.com/24791536/101621182-b75d4780-3a15-11eb-99fd-272bdd29c63c.png)

**Back-end** - Errore non riscontrato. 

![Articoli  Modifica - Quickstart ItaliaPA - Amministrazione](https://user-images.githubusercontent.com/24791536/101621214-c17f4600-3a15-11eb-8d5b-88231b1ae701.png)

### System information
Release [attachments 3.2.6](http://jmcameron.net/attachments/updates/3.2.6/)

**Comment by eshiol** [comment]
Mi confermate che il problema si manifesta solo con il template ItaliaPA? Potete provare con il template Protostar - Default.

**Comment by Knock-Out** [comment]
Anomalia in Attachments. Il problema si manifesta anche con il template **Protostart 1.0**. 

> ### System information
> Release [attachments 3.2.6](http://jmcameron.net/attachments/updates/3.2.6/)

**Comment by eshiol** [comment]
Il problema è da imputare al componente.

**Comment by Knock-Out** [comment]
**Nota:** Nella parte visuale dell'articolo è possibile effettuare le modifiche tramite **pencil icon** (no modifica articolo).

![#22 - #310 (1)](https://user-images.githubusercontent.com/24791536/101668858-610dfa00-3a51-11eb-8e8b-41265bfd1c02.png)


![#22 - #310 (2)](https://user-images.githubusercontent.com/24791536/101668787-49367600-3a51-11eb-9aca-db305b0a0bad.png)
