### ISSUE TITLE
Modifica articoli da front end con browser Edge

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#320]
### Steps to reproduce the issue
Accedo al sito tramite il browser Edge, effettuo il login da front end come amministratore per modificare un articolo

### Expected result
Mi aspetto di visualizzare l'icona per la modifica degli articoli da front end

### Actual result
Aprendo lo stesso articolo con Edge, con le medesime configurazioni, il pulsante di modifica da front end non si visualizza mentre in Chrome l'icona è correttamente visualizzata.

### System information (as much as possible)
Joomla 3.9.20
Template ItaliaPA 3.9.0.17
Microsoft Edge Versione 83.0.478.64 (Build ufficiale) (64 bit)
Mozilla Firefox Versione 78.0.2 (64 bit)

**Comment by eshiol** [comment]
Problema non verificato con
Edge Version 87.0.664.47 (Official build) (64-bit)
Firefox 83.0 (64 bit)
