### ISSUE TITLE
Adattare stile template a plugin system content Multicategories per editing articoli da frontend

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#321]
### Steps to reproduce the issue
Creo un nuovo articolo da front end; voglio aggiungere una categoria ulteriore tramite il plugin aggiuntivo ["system content Multicategories"](https://extensions.joomla.org/extension/content-multicategories/).

### Expected result
Il layout della pagina di creazione dell'articolo presenta anche per questo componente aggiuntivo il layout di ItaliaPA

### Actual result
Non è presente lo stile del template.

### System information (as much as possible)
Joomla 3.9.20
ItaliaPA 3.9.0.17

### Additional comments
![screen categorie aggiuntive](https://user-images.githubusercontent.com/12257435/90659494-0738b880-e245-11ea-9ed5-4dcaa6988f80.png)

**Comment by eshiol** [comment]
Va identificato il tipo di campo utilizzato.

**Comment by atodaro** [comment]
Deve essere un campo con elenco a discesa che consente di selezionare le categorie di articoli presenti, stesso layout del campo omologo della tab "pubblicazione"

**Comment by eshiol** [comment]
Il plugin è scritto in modo da non poter essere adeguato tramite override. Se vuoi, puoi modificare il codide del plugin per adeguarlo allo stile a ItaliaPA.
Modifica il file /plugins/system/contentmulticategories/contentmulticategories.php a partire dalla linea 76:
```
        $html = '
        <div class="tab-pane" id="contentmulticategories">
            <div class="control-group">
                <label for="contentmulticategories_multi_categories" class="control-label" title="" >'.JText::_('JSELECT').'</label>
                <div class="controls">
                    <select name="contentmulticategories[categories][]" id="contentmulticategories_multi_categories" multiple="multiple" size="10">
                            '.JHtml::_('select.options', $options, 'value', 'text', $selectedCats).'
			        </select>
                </div>
            </div>
        </div>
		';
```
sostituisci con il seguente codice
```
	$template = JFactory::getApplication()->getTemplate();
	if ($template == 'italiapa')
	{
		$html = '
		<div class="Form-field" id="contentmulticategories">
			<label for="contentmulticategories_multi_categories" class="Form-label" title="" >'.JText::_('JSELECT').'</label>
			<select name="contentmulticategories[categories][]" id="contentmulticategories_multi_categories" class="inputbox" multiple="multiple" size="10">
				'.JHtml::_('select.options', $options, 'value', 'text', $selectedCats).'
			</select>
		</div>';
	}
	else
	{
		$html = '
		<div class="tab-pane" id="contentmulticategories">
			<div class="control-group">
				<label for="contentmulticategories_multi_categories" class="control-label" title="" >'.JText::_('JSELECT').'</label>
				<div class="controls">
					<select name="contentmulticategories[categories][]" id="contentmulticategories_multi_categories" multiple="multiple" size="10">
						'.JHtml::_('select.options', $options, 'value', 'text', $selectedCats).'
					</select>
				</div>
			</div>
		</div>';
	}
```
