### ISSUE TITLE
Modifica articoli da front end con browser Firefox

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#323]
### Steps to reproduce the issue
Accedo al sito tramite il browser Firefox, effettuo il login da front end come amministratore per modificare un articolo

### Expected result
Mi aspetto di visualizzare l'icona per la modifica degli articoli da front end

### Actual result
Aprendo lo stesso articolo con Firefox, con le medesime configurazioni, il pulsante di modifica da front end non si visualizza mentre in Chrome l'icona è correttamente visualizzata.

### System information (as much as possible)
Joomla 3.9.20
Template ItaliaPA 3.9.0.17
Mozilla Firefox Versione 78.0.2 (64 bit)

**Comment by eshiol** [comment]
Problema non riscontrato con Mozilla Firefox 69.0.3 (64 bit), 72.0.2 (64 bit), 83.0 (64 bit).
