### ISSUE TITLE
Modulo Elenco categorie: anomalia descrizione categorie

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#325]
### Steps to reproduce the issue
Creo un modulo di tipo "Elenco Categorie" in posizione featured; in "descrizione categorie" seleziono "NO".

### Expected result
Il modulo non mostra la descrizione delle categorie.
### Actual result
Il modulo mostra la descrizione delle categorie.

![elenco categorie](https://user-images.githubusercontent.com/12257435/100499370-645bd880-3169-11eb-8d37-fb84c466ed9f.png)

![descrizione categorie](https://user-images.githubusercontent.com/12257435/100499382-7b9ac600-3169-11eb-9c22-dbafee0bd992.png)

### System information (as much as possible)
Joomla 3.9.23
ItaliaPA: alpha 17

### Additional comments
Screenshot di configurazione
![modulo](https://user-images.githubusercontent.com/12257435/100524470-baa43800-31b8-11eb-9ec6-8b3fdec93b86.png)
![avanzate](https://user-images.githubusercontent.com/12257435/100524472-bf68ec00-31b8-11eb-9ea2-4d2659f95142.png)

Rispetto ad un modulo standard, nella tab "modulo" ho selezionato per sottocategorie "SI".
Rispetto ad un layout predefinito, ho selezionato il layout Masonry, con stile del modulo "lg"

**Comment by eshiol** [comment]
Indicare se si tratta di modulo Elenco articoli o elenco categorie
Indicare il layout
Indicare lo stile del modulo
