### ISSUE TITLE
Modulo menù con layout lead: rimozione frecce indicatrici

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#332]
### Steps to reproduce the issue
Creo un modulo menu.
Posiziono il menu in posizione "Lead"
Da Avanzate, seleziono il layout "Lead"

### Expected result
Il modulo mostra le immagini di ciascuna voce di menu **senza** le frecce attive

### Actual result
Il modulo mostra le immagini di ciascuna voce di menu **con** le frecce attive come da immagine
![lead menu](https://user-images.githubusercontent.com/12257435/100537712-098ab580-322b-11eb-9ab1-2c9eb45f76a0.png)

### System information (as much as possible)
ItaliaPA alpha 7

### Additional comments
La funzionalità non è prevista dal webtoolkit: la issue è aperta per valutare l'opportunità di modificare questo tipo di layout.

**Comment by eshiol** [comment]
La funzionalità è prevista dal [WebToolkit - Leads Utilità](https://italia.github.io/design-web-toolkit/components/detail/leads--utilita.html), ma se si usano immagini il risultato non è gradevole.
