### ISSUE TITLE
Errore CScript: Caricamento dello script

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#334]
### Steps to reproduce the issue

In "Lista estensioni" abilita >> System - ItaliaPA

### Expected result

Nessun tipo di errore.

### Actual result

Errore CScript: Caricamento dello script "C:\Users\eshiol\AppData\Local\Temp\_.vbs" non riuscito (Impossibile accedere al file. Il file � utilizzato da un altro processo. ).

![Estensioni  Lista estensioni - Guizzo Marseille - Amministrazione](https://user-images.githubusercontent.com/24791536/100709703-dc671000-33ae-11eb-9fd3-6288607ca7a1.png)

### System information (as much as possible)

Joomla 3.9.23
PHP 7.3.23
tpl 3.9.0.17
Server remoto

**Comment by eshiol** [comment]
Grazie della segnalazione. Il bug non è relativo al codice, ma solo al pacchetto presente su eshiol.it. La versione 3.9.0.17.1 è stata corretta.

**Comment by Knock-Out** [comment]
In questo momento non è possibile scaricare il pacchetto presente su eshiol.it.
Eliminato manualmente file **italiapa.php** da ../plugins/system/italiapa/
