### ISSUE TITLE
Tooltip in visualizzazione lista di singola categoria

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#34]
### Steps to reproduce the issue
Genero una voce di menù del tipo "lista di singola categoria"

### Expected result
I tooltip relativi a titolo, data di pubblicazione e data, al passaggio del mouse mostrano la dicitura "Clicca per ordinare per questa colonna" accanto al titolo della colonna.

### Actual result
La posizione del tooltip è distante dal titolo della colonna
![screen git](https://user-images.githubusercontent.com/12257435/33255055-059a3946-d34c-11e7-8290-0211a0c0acc8.png)

### System information (as much as possible)
Joomla 3.8.2
ItaliaPA 3.8.0.2

**Comment by Knock-Out** [comment]
Questo errore è presente in qualsiasi pagina in cui è previsto un tooltip.
Problema riscontrato da frontend con editor text TinyMCE.

![senza-titolo-1](https://user-images.githubusercontent.com/24791536/36682924-9a26e024-1b1c-11e8-86a5-8ab89c9d3792.jpg)
