### ISSUE TITLE
JLIB_INSTALLER_ERROR_SQL_ERROR

### ISSUE THREAD

**Issue by maddom73** [retepasw/joomla-italiapa#343]
### Steps to reproduce the issue

I'm not able to finish the italiapaswjoomla installation

### Actual result

On the step 2 I get JLIB_INSTALLER_ERROR_SQL_ERROR and the installation process stops there

![Schermata del 2020-12-12 01-40-56](https://user-images.githubusercontent.com/5103247/101982222-92194500-3c72-11eb-8190-87d406674f74.png)

### System information (as much as possible)

XAMP 7.2.34 + MariaDB + PHP  + MySQL

**Comment by eshiol** [comment]
Dallo screeshot che hai allegato si evince che il problema è relativo all'installazione del quickstart ItaliaPAsW.

Questo canale è relativo al solo Template ItaliaPA.
