### ISSUE TITLE
Ridimensionamento immagini negli articoli

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#362]
### Steps to reproduce the issue
1. Creo un articolo e inserisco un'immagine articolo esteso con allineamento a destra
2. Creo un articolo e inserisco un'immagine articolo esteso con allineamento a sinistra
3. Creo un articolo e inserisco un'immagine articolo esteso con allineamento "nessuno"

### Expected result
1. 2. 3. L'immagine dell'articolo si ridimensiona correttamente.

### Actual result
1. L'immagine dell'articolo si ridimensiona correttamente.
2. e 3. Allineamento a sinistra o "nessuno": l'immagine dell'articolo esteso non si ridimensiona come nel caso dell'immagine a destra.
![Articolo immagine nessuno](https://user-images.githubusercontent.com/12257435/103475788-aacbd500-4db0-11eb-94e0-22e26217a82a.png)
![Articolo immagine sinistra](https://user-images.githubusercontent.com/12257435/103475789-ab646b80-4db0-11eb-8e04-3df444e17ca3.png)
![Articolo immagine destra](https://user-images.githubusercontent.com/12257435/103475790-ab646b80-4db0-11eb-9aac-ffd422987a38.png)

### System information (as much as possible)
Joomla! .23
ItaliaPA: Template | 3.9.0.18-dev

**Comment by eshiol** [comment]
Non si tratta di un bug ma di un effetto voluto. L'immagine viene inserita in posizione right come fosse un modulo. Il suo utilizzo diventa chiaro se si aggiunge un modulo in posizione right.
