### ISSUE TITLE
Mega Menu - Item "Accedi" is not in the right position

### ISSUE THREAD

**Issue by gmassolo** [retepasw/joomla-italiapa#364]
### Steps to reproduce the issue
[https://web.liceogiovio.edu.it/_sito2020/](url)

### Expected result
"Accedi" should be at the right of the main Menu

### Actual result
"Accedi" is not in the Main Manu but in Servizi->Modulistica and the visualisation in bad

### System information (as much as possible)

PHP 7.3
Joomla! 3.9.10
ItaliaPA 3.9.0.17.2

### Additional comments

This is my first post here.
I hope to do well.

**Comment by Knock-Out** [comment]
Dovresti descrivere tutti i passaggi tecnici che hai effettuato per la realizzazione del megamenu perché in questo modo è impossibile indagare. Potrebbe essere un problema di codice (che non rileviamo) come un problema nelle impostazioni del tuo sito.

**Comment by gmassolo** [comment]
ho semplicemente aggiunto voci di menu (a partire dal modello PASW) , ma non ho mai toccato il menu principale
non saprei ricostruire i passaggi
forse oltre un tot di voci il menu non riesce a gestire, però ho aggiunto solo voci secondarie (o rinominato le presenti)


posso dire cosa fare per far sparire il problema, cioè come rimuovere passo a passo le voci di menu fino a quando si presenta il problema

oppure potrei reinstallare il modello su qualche spazio web riaggiungere tutti i menu fino a quando si presenta il problema, se proprio serve

non ho mai modificato nessuna impostazione, visto che il sito è in hosting

unico dubbio va bene PHP 7.3?

**Comment by Knock-Out** [comment]
> oppure potrei reinstallare il modello su qualche spazio web riaggiungere tutti i menu fino a quando si presenta il problema, se proprio serve

Ok.

> unico dubbio va bene PHP 7.3?

Si, e ok.

**Comment by Knock-Out** [comment]
> posso dire cosa fare per far sparire il problema, cioè come rimuovere passo a passo le voci di menu fino a quando si presenta il problema

Ok.

> unico dubbio va bene PHP 7.3?

Si.

**Comment by mariantanase** [comment]
Un suggerimento sarebbe quello di aggiornare joomla visto che hai una versione abbastanza obsoleta (luglio 2019), ma non significa che questo ti risolve il problema.

**Comment by gmassolo** [comment]
Steps to reproduce the issue
https://web.liceogiovio.edu.it/_sito2020/

MegaMenu
Menu SERVIZI : se sospendo tutte le voci, ma lascio attiva la voce principale SERVIZI, la scritta ACCEDI ricompare in posizione corretta.
Se sospendo la voce principale servizi (e conseguentemente tutte le sottovoci) la scritta ACCEDI compare in posizione scorretta nel menu precedente (che in questo caso è NOTIZIE)

**Comment by gmassolo** [comment]
Credo di avere risolto.

C'era una voce di menu con accesso pubblic come sottovoce di Areee riservate che invece ha accesso registered.
Impostando la voce  a registered ora  la scritta ACCEDI torna in posizione corretta.

Ringrazio  tutti per la pazienza.
Vi chiedo a questo punto se è in generale un errore settare come pubblic una sottovoce di una voce con accesso registered o se è una errata risposta del template o di joomla.

**Comment by atodaro** [comment]
è un errore assegnare una voce "public" al di sotto di una voce "registered".
Note: issue da modificare in "closed"
