### ISSUE TITLE
Modulo elenco categorie: anomalia descrizione categorie

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#367]
### Steps to reproduce the issue
Creare una categoria con più sottocategorie
Creare un modulo Elenco Categorie con layout focus associata alla categoria padre appena creata
Nelle impostazioni del modulo, selezionare "no" per la "descrizione categoria"

### Expected result
Il modulo mostra soltanto i titoli delle sottocategorie

### Actual result
![test elenco categorie front](https://user-images.githubusercontent.com/12257435/103761051-53c73980-5016-11eb-9237-3307e8cf5d46.png)

### System information (as much as possible)
Nigthly build 3.9.0.18

**Comment by eshiol** [comment]
Anomalia confermata.
