### ISSUE TITLE
Campo doppio "Immagine Hero news"

### ISSUE THREAD

**Issue by mariantanase** [retepasw/joomla-italiapa#371]
### Steps to reproduce the issue
Probabilmente non è una issue. Ma volevo segnalare che dopo l'aggiornamento automatico dalla 3.9.0.17.2 alla 3.9.0.18, mi risultano 2 voci uguali del campo aggiuntivo "Immagine Hero news". Probabilmente per il fatto che nel mio ambiente di test, in precedenza, avevo creato manualmente quel campo, e adesso con l'aggiornamento risulta doppio. Ho dovuto cancellare uno. 

### Actual result
![Screenshot_2021-01-07 Articoli Campi aggiuntivi - Comune di Prova - Amministrazione](https://user-images.githubusercontent.com/3976174/103891648-8478a300-50ea-11eb-87a9-3588bb0c2239.png)

### System information (as much as possible)
Joomla 3.9.23
PHP 7.4.4
MySQL 8.0.16

**Comment by eshiol** [comment]
Il campo **_image-heronews_** va lasciato, l'altro, **_immagine-heronews_**, va cancellato.
