### ISSUE TITLE
Hero News: visualizzazione immagine introduzione degli articoli introduttivi

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#381]
### Steps to reproduce the issue
Creo una voce di menù che sarà la voce principale del sito e quindi la homepage.
La voce di menù è di tipo: Articoli » Articoli in evidenza di tutte le categorie (layout: Hero news)
Imposto il layout in modo che siano visibili:
N° Articoli principali: valore maggiore di 1 per avere lo slider
**N° articoli introduttivi**: 6 
N° colonne: 2
N° link da 0 a valori superiori

Gli articoli utilizzati per essere messi "in evidenza" devono avere ciascuno un'**Immagine Introduzione** mentre per l'effetto heronews imposterò il campo aggiuntivo, secondo le recenti possibilità introdotte dal template.
Un esempio di impostazione della tab layout della voce di menù è il seguente:
![screenshot-paswjoomla net-2021 01 15-22_39_50](https://user-images.githubusercontent.com/12257435/104781404-ade89d00-5782-11eb-848f-c9b77beef5ef.png)

### Expected result
Mi aspetto che gli **Articoli Introduttivi** mostrino l'**immagine di introduzione** come in questa simulazione grafica
![139376024_500343804321078_3622513188354508874_n](https://user-images.githubusercontent.com/12257435/104781763-55fe6600-5783-11eb-86c0-d966d5ed3ab7.jpg)

### Actual result
Attualmente le "immagini di introduzioni" non possono essere visualizzate.
Tra le impostazioni della voce di menu, nella tab "Opzioni" manca il comando per poter scegliere se mostrare o meno le immagini
Il risultato attuale, pertanto, è il seguente:
![screenshot-paswjoomla net-2021 01 15-22_47_48](https://user-images.githubusercontent.com/12257435/104781969-c1e0ce80-5783-11eb-9eea-daf0ee851f34.png)

### System information (as much as possible)
Joomla 3.9.24
ItaliaPA: 3.9.0.18 (release di gennaio 2021)

**Comment by eshiol** [comment]
Bisogna esplicitare i tre scenari di allineamento immagine: destra, sinistra, nessuno
![image](https://user-images.githubusercontent.com/12718836/104783588-a4613400-5786-11eb-9ad2-eeb0445a1068.png)

**Comment by atodaro** [comment]
L'immagine si allinea secondo le impostazioni settate nell'articolo, a destra o a sinistra; in caso di nessun allineamento preferirei, ma è una proposta personale, l'allineamento a sinistra. 
L'immagine si posiziona lateralmente rispetto al titolo e al testo introduttivo dell'articolo, una sorta di "teal" con immagine laterale.

**Comment by atodaro** [comment]
Actual result
![Homepage attuale](https://user-images.githubusercontent.com/12257435/104784617-f4d99100-5788-11eb-81d2-9b24a625f542.jpg)
Questo è il risultato attuale con la visualizzazione dei link.

La "Teal" con immagine laterale dovrebbe essere invece così
![Home come sarà](https://user-images.githubusercontent.com/12257435/104784754-441fc180-5789-11eb-906e-70f5863629f9.jpg)
Questa immagine indica l'aspetto che dovranno avere gli articoli introduttivi
