### ISSUE TITLE
Referenza esterna non linkata

### ISSUE THREAD

**Issue by mariantanase** [retepasw/joomla-italiapa#384]
### Steps to reproduce the issue
Creo un articolo, e nella scheda "Pubblicazione" inserisco un testo nel campo riferimento chiave. Nel campo Referenza esterna inserisco il link sia nel formato www.dominio.it sia http://www.dominio.it

### Expected result
Il testo e l'icona dovrebbero essere linkati.

### Actual result
L'articolo pubblicato mostra la "fonte" con icona e testo NON-linkato inserito nella referenza esterna.
![Screenshot_2021-01-20 Nulla ullamcorper](https://user-images.githubusercontent.com/3976174/105147979-255f5900-5b02-11eb-878d-1c0a9ede1360.png)

### System information (as much as possible)
Joomla 3.9.24
Template ItaliaPA 3.9.0.18
PHP 7.4.4

### Additional comments
In passato c'era un'altra issue simile #6

**Comment by Knock-Out** [comment]
Problema non rilevato.

![Articoli  Modifica - Demo tpl ItaliaPa - Amministrazione](https://user-images.githubusercontent.com/24791536/105149704-209ba480-5b04-11eb-91c6-6a1661e9311f.png)

![Notizie 4](https://user-images.githubusercontent.com/24791536/105149700-1ed1e100-5b04-11eb-94ef-4d2bc56c1994.png)
