### ISSUE TITLE
Modulo menù treeview: chiusura sotto voci di menu

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#39]
### Steps to reproduce the issue
Creo un modulo menù, in posizione "right", con layout "treeview"

### Expected result
Le sottovoci di menù sono visibili solo dopo aver cliccato sull'indicatore
![screenshot-paswjoomla net-2017-12-01-17-55-43-852](https://user-images.githubusercontent.com/12257435/33493599-e55b4ae4-d6c0-11e7-88f7-2250ef438b3d.png)

### Actual result
Le sotto voci di menù, appena si accede alla pagina, sono già tutte esplose
![screenshot-paswjoomla net-2017-12-01-17-57-00-890](https://user-images.githubusercontent.com/12257435/33493662-1226295e-d6c1-11e7-8938-320a161c9f85.png)

### System information (as much as possible)
Joomla 3.8.2.
ItaliaPA 3.8.0.3

### Additional comments
Lo stesso tipo di visualizzazione con menù esploso si ha nel menù hamburger da mobile; la navigazione risulta fastidiosa e diminuisce l'usabilità del sito.

**Comment by eshiol** [comment]
Comportamento confermato
