### ISSUE TITLE
Sito di aggiornamento "Content - Vote for ItaliaPA Plugin"

### ISSUE THREAD

**Issue by mariantanase** [retepasw/joomla-italiapa#391]
### Steps to reproduce the issue
:arrow_forward: Estensioni > Gestione > Aggiorna
:arrow_forward: Pulisci Cache
:arrow_forward: Cerca Aggiornamenti

### Expected result
Nessun aggiornamento trovato

### Actual result
Avviso di file non trovato (https://www.eshiol.it/files/italiapa/plg_content_ipavote.xml)
![Screenshot_2021-01-25 Estensioni Aggiorna - Nome della Pubblica Amministrazione - Amministrazione](https://user-images.githubusercontent.com/3976174/105719472-977cd700-5f22-11eb-9965-e18c6d7d4b22.png)

### System information (as much as possible)
Joomla 3.9.24
Template ItaliaPA 3.9.0.18
PHP 7.4.4

**Comment by Knock-Out** [comment]
Prova in questo modo: 

modifica la stabilià minima in Alpha

Estensioni
Siti di aggiornamento
Opzioni

**Comment by Knock-Out** [comment]
Aggiorna l'ultima versione del template.

**Comment by mariantanase** [comment]
> 
> 
> Aggiorna l'ultima versione del template.

C'e già "ItaliaPA 3.9.0.18"

**Comment by Knock-Out** [comment]
@mariantanase intendevo la nightly (19.dev).

**Comment by mariantanase** [comment]
Ok, sovrascritto con la staging attuale ma ancora avvisi.
"Aggiornamento::Estensione: Impossibile parserizzare https://www.eshiol.it/files/italiapa/plg_content_ipavote.xml"

In effetti, provando a caricare il riferimento al file xml "https://www.eshiol.it/files/italiapa/plg_content_ipavote.xml" in browser, esce:
"_Non sei autorizzato a vedere questa risorsa_"

**Comment by mariantanase** [comment]
Confermo che adesso non esce più quel avviso.
