### ISSUE TITLE
Colore titolo articolo layout categoria blog per articoli "registered"

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#4]
### Steps to reproduce the issue
Genero una voce di menù del tipo "categoria blog"; gli articoli pubblicati con permessi "registered" mostrano un colore del titolo grigio chiaro, poco visibile e con poco contrasto sfondo - testo.

### Expected result
Il colore del testo del titolo dovrebbe mantenere il colore nero di base.
![screen issue2_1](https://user-images.githubusercontent.com/12257435/32683357-f2a6ba18-c67a-11e7-9656-f4e70349a5c1.png)

### Actual result
_Vedi testo "circolare n.39..."_
![screen issue2](https://user-images.githubusercontent.com/12257435/32683181-9a5faf32-c679-11e7-907b-0abeb152000f.png)

### System information (as much as possible)
Ver. Joomla! 3.8.2
Ver. Template 3.8.0.1

**Comment by eshiol** [comment]
Comportamento confermato per tutti gli articoli con titolo not linkable
