### ISSUE TITLE
Errore Megamenu - multicolonna

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#401]
### Steps to reproduce the issue >> #372

- 1 Modulo menu posizione >> mainmenu
- 1 Main menu 
- - -
- 1 voce di menu di 1° livello (Servizi)
- 1 voce di menu di 2° livello (Columns-2)
- 4 voci di menu di 3° livello (Servizi 2/3/4/5)

![Menu  Voci di menu  Main Menu  - Demo tpl ItaliaPa - Amministrazione](https://user-images.githubusercontent.com/24791536/106916269-4087b680-6707-11eb-8536-68fa05272651.png)

Nella voce di menu di **2° livello** (Columns-2) inserire la classe del link CSS `columns-2`

### Expected result

![Home (1)](https://user-images.githubusercontent.com/24791536/106917556-a9bbf980-6708-11eb-8d5f-9a4e71cdfd63.png)

### Actual result

![Home](https://user-images.githubusercontent.com/24791536/106916901-00750380-6708-11eb-91a1-67d5e5b9182d.png)

### System information (as much as possible)

Joomla! 3.9.24 
ItaliaPA 3.9.0.19-dev
Nightly Builds 2c5cd8d

### Additional comments

Attualmente il multicolonna funziona solo se si imposta nella voce di menu di 1° livello (Servizi) un ulteriore voce di menu di 2° livello (Servizi 6) [Vedere immagine Expected result]

![Menu  Voci di menu  Main Menu  - Demo tpl ItaliaPa - Amministrazione (1)](https://user-images.githubusercontent.com/24791536/106918041-251dab00-6709-11eb-82b2-c5be91e9c694.png)

**Comment by eshiol** [comment]
Il problema dovrebbe essere risolto dalla PR #404
