### ISSUE TITLE
Errore visualizzazione Icon-chevron-last e Icon-chevron-first

### ISSUE THREAD

**Issue by NioBee** [retepasw/joomla-italiapa#402]
### Steps to reproduce the issue

Creare un menu Categoria Blog contenente un numero di articoli che si estende su più pagine

### Expected result

![Comunicazioni pagine seguenti ok](https://user-images.githubusercontent.com/41695549/107024527-73ce5200-67a8-11eb-8d06-31e35af46384.PNG)

### Actual result

![Comunicazioni pagine seguenti](https://user-images.githubusercontent.com/41695549/107024542-77fa6f80-67a8-11eb-80ae-2222d059a296.PNG)

### System information (as much as possible)

Template ItaliaPA 3.9 Beta 2 (build 19)
Joomla 3.9.24
Prove effettuate su sito in modalità live staging ergonet

**Comment by eshiol** [comment]
Il problema dovrebbe essere risolto dalla PR #405

In attesa del rilascio della versione corretta del template è possibile inserire in seguente codice nel file user.css

```
svg.Icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
```

Per istruzioni su come procedere: [Personalizzazione del template ItaliaPA](https://www.eshiol.it/it/c0bc)
