### ISSUE TITLE
Formattazione titolo articoli categoria blog layout Masonry

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#407]
### Steps to reproduce the issue
Creare una voce di menu Articoli - Categoria blog (layout: Masonry)
Nella categoria prevedere articoli riservati agli utenti registrati.

### Expected result
Nella pagina blog I titoli degli articoli riservati sono visualizzati con la stessa formattazione assegnata ai titoli degli articoli "public"

### Actual result
I titoli degli articoli riservati si visualizzano di colore più chiaro.
![layout blog](https://user-images.githubusercontent.com/12257435/107122634-267ddd80-6899-11eb-8166-a4bfcdce5b60.png)

### System information (as much as possible)
Joomla .24
ItaliaPA Beta2

**Comment by Knock-Out** [comment]
Comportamento anomalo confermato. ☑️

![403 406 Categoria blog - layout Masonry](https://user-images.githubusercontent.com/24791536/107142462-5aa3dd80-692f-11eb-8f91-6ffd9f3760c7.png)

**Comment by NioBee** [comment]
Stesso comportamento sul mio sito.
