### ISSUE TITLE
Icone grandi su form di login

### ISSUE THREAD

**Issue by mariantanase** [retepasw/joomla-italiapa#412]
### Steps to reproduce the issue
Creato nuovo modulo tipo login form e pubblicato nella posizione right.
Se "Visualizzazione etichette" è impostato su "Testo", il form si vede corretto.
Se "Visualizzazione etichette" è impostato su "Icone", il form mostra icone grandi.

### Actual result

![Screenshot_2021-02-12 Articolo](https://user-images.githubusercontent.com/3976174/107782318-338f4680-6d49-11eb-8994-101aeb0e08f1.png)

### System information (as much as possible)
Joomla 3.9.24
Template ItaliaPA 3.9.0.19
PHP 7.4.4

**Comment by eshiol** [comment]
Prova la PR #405

**Comment by mariantanase** [comment]
> 
> 
> Prova la PR #405

Perfetto. Grazie @heliosciancio 
![Screenshot_2021-02-15 Articolo](https://user-images.githubusercontent.com/3976174/107920725-b7c21380-6f6d-11eb-8657-46e8abca9fce.png)
