### ISSUE TITLE
Tooltip per firma circolari

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#417]
### Steps to reproduce the issue
Creo un articolo per utenti registrati, associando la toolbar per la firma delle circolari.
Situazione 1: Firmo una comunicazione.
Situazione 2: Accedo all'articolo come utente con permessi "Special" e clicco sull'icona per la visualizzazione dei report

### Expected result
Situazione 1: Il tooltip relativo all'icona per l'espressione della "firma circolari" è formattato secondo lo stile del template
Situazione 2: Il tooltip relativo all'icona del report di "firma circolari" è formattato secondo lo stile del template

### Actual result
Situazione 1: Il tooltip relativo all'icona per l'espressione della "firma circolari" non è formattato secondo lo stile del template
Situazione 2: Il tooltip relativo all'icona del report di "firma circolari" non è formattato secondo lo stile del template

![screen firma circolare](https://user-images.githubusercontent.com/12257435/109051118-7999c200-76da-11eb-9d64-4e9ed8153496.jpg)

### System information (as much as possible)
Template ver. 20 Dev  - febbraio 2021

**Comment by eshiol** [comment]
#420
