### ISSUE TITLE
Menu contestuali e menu burger

### ISSUE THREAD

**Issue by ellegi178** [retepasw/joomla-italiapa#42]
### Steps to reproduce the issue
Tra le scelte che si possono fare nell'impostazione del menu burger sul backend di Joomla, non ne trovo che permettano di renderlo in qualche modo contestuale al punto del sito in cui si è.

### Expected result
Non riesco a trovare se e in che punto le linee guida designItalia chiariscano il punto, ma analizzando i siti di PA che hanno cercato di recepire le linee guida, mi sembra che su questo punto si proceda un po' in ordine sparso, con soluzioni più o meno efficaci: 
- meno efficaci: riportare il menu nel corpo della pagina, che spesso significa dopo così tanti blocchi di contenuto che l'utente non ha più la percezione dell'articolazione dei contenuti in cui quella sezione  si sviluppa.
- più efficaci: doppio menu, con il menu burger tradizionale e un secondo menu "Navigazione" posto su una linea come sul sito del Ministero dello Sviluppo Economico: oltre al menu burger con i primi livelli, un altro menu con il livelli/pagine sottostanti e quelli (e solo quelli) superiori alla pagina su cui si è (es. [aprire il menu contestuale sulla pagina sulla produzione di gas naturale su display sotto i 992px](http://www.sviluppoeconomico.gov.it/index.php/it/energia/gas-naturale-e-petrolio/gas-naturale/produzione))

Chiedo però se non vi sembra che due menu possano disorientare gli utenti meno scaltri. Dal punto di vista che sto pradicando io (siti di piccole amministrazioni locali con un numero limitato di livelli) mi piacerebbe molto che le due funzionalità dei due menu fossero riunite nel burger. Se può aiutare a chiarire la mia esigenza, vi mando un print screen del menu che abbiamo provato a svillupare con un piccolo intervento sul codice.
![menu](https://user-images.githubusercontent.com/33519380/33615154-a351a1cc-d9d9-11e7-9bfc-8b276ed40cc5.png)

### Additional comments
Ringrazio ancora chi ha avuto la pazienza e la capacità di sviluppare il template e chi potrà darmi un riscontro. Ciao

**Comment by atodaro** [comment]
Spero di aver compreso la richiesta: il link che hai postato visualizza un menù aggiuntivo in posizione "right" già previsto dal template. 
In questo caso puoi creare un modulo "menù" in posizione "right" con layout "treeview" e classe header  "u-text-h3 u-color-60 u-padding-bottom-xxs" 
Un esempio in questa pagina:
[demo menù laterale](https://paswjoomla.net/ItaliaPAsW/trasparenza)

**Comment by eshiol** [comment]
Devi creare un modulo menu in posizione right da associare alla pagina interessata.
