### ISSUE TITLE
Visualizzazione errata delle sotto-voci di menu di primo livello

### ISSUE THREAD

**Issue by mariantanase** [retepasw/joomla-italiapa#421]
### Steps to reproduce the issue
1. Sito test con Joomla 3.9.24 e il template ItaliaPA 3.9.0.19
2. Aggiornamento Joomla alla 3.9.25
3. Installazione pacchetto pkg_italiapa-3.9.0.20.zip.
Risultato e che le sotto-voci di menu compaiono adesso su più colonne e con un font molto grande .

### Expected result
![voci-menu-ok](https://user-images.githubusercontent.com/3976174/109793507-054caa80-7c15-11eb-8994-a27abe15742f.png)

### Actual result
![voci-menu-err](https://user-images.githubusercontent.com/3976174/109793550-139ac680-7c15-11eb-8f8a-25b69169f6cb.png)

### System information (as much as possible)
Joomla 3.9.25
PHP 7.4.4

### Additional comments
Sembra che il problema è causato delle modifche nel "**megamenu.php**"
Sostituendolo con quello della versione precedente 3.9.0.19, problema scompare.

**Comment by eshiol** [comment]
Non si tratta di un errore ma del ripristino del comportamento predefinito di it WebToolkit. 

Per ulteriori informazioni consulta la PR #404
