### ISSUE TITLE
Mancata formattazione tooltip modifica moduli e menu da front end

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#422]
### Steps to reproduce the issue
Imposto il cms in modo da consentire la modifica inline dei moduli e dei menu da front end.
Accedo al sito da front end come super user per la modifica dei menu e dei moduli.
### Expected result
I tooltip per la modifica dei moduli e dei menu sono formattati con lo stile del toolkit

### Actual result
I tooltip per la modifica non sono formattati correttamente, come indicato nelle immagini sottostanti.
![modifica menu screen](https://user-images.githubusercontent.com/12257435/109837736-c551eb80-7c45-11eb-8720-7d275f747635.jpg)
![screen tooltip modifica moduli front end](https://user-images.githubusercontent.com/12257435/109837738-c5ea8200-7c45-11eb-880f-cf06230e0f20.jpg)

### System information (as much as possible)
Joomla! 3.9.25
ItaliaPA 3.9.20 RC1

**Comment by Knock-Out** [comment]
Comportamento anomalo confermato. 

![Senza-titolo-1](https://user-images.githubusercontent.com/24791536/109838583-96884500-7c46-11eb-8d5a-4611dc5f37d5.jpg)
