### ISSUE TITLE
Hamburger menu, Megamenu - errore di visualizzazione sotto voci senza titolo

### ISSUE THREAD

**Issue by vittorioalfieri** [retepasw/joomla-italiapa#426]
### Steps to reproduce the issue
Creare un sottomenu principale, con una sola lista senza Titolo, usando un separatore come spiegato nella issue #404.
Nel menu esteso tutto funziona correttamente, ma attivando l'hamburger menù le sotto voci non appaiono.

il problema sembra essere che in presenza di una voce di menu di tipo:
`<span class="separator u-hidden u-visibilityHidden">(separatore)</span>`

il sottomenù ora è: `<ul role="group" aria-hidden="true">`

invece dovrebbe essere: `<ul role="group" aria-hidden="false">`

### Expected result

![image](https://user-images.githubusercontent.com/18733784/112497828-3dfc2180-8d86-11eb-9461-2b32e6c19629.png)

### Actual result
è possibile verificare il problema sul sito: https://test.iismarconipieralisi.it

![image](https://user-images.githubusercontent.com/18733784/112497003-7bac7a80-8d85-11eb-9035-98649e5ec291.png)

### System information (as much as possible)
Joomla 3.9.25
ItaliaPA 3.9.0.20

**Comment by Knock-Out** [comment]
@vittorioalfieri Utilizza Titolo sepratore.

**Comment by vittorioalfieri** [comment]
Se uso titolo separatore poi il titolo si vede invece come da issue #404
non si deve vedere.

Il Gio 25 Mar 2021, 18:12 Claudio Rosselli ***@***.***> ha
scritto:

**Comment by vittorioalfieri** [comment]
Se uso titolo separatore poi il titolo si vede, invece come da issue #404 non si deve vedere.

![image](https://user-images.githubusercontent.com/18733784/112595522-d4722680-8e0a-11eb-90b9-d756dd2d78a7.png)

**Comment by eshiol** [comment]
La #404 si riferisce esclusivamente al megamenu. Al momento la cosa è gestibile nel burgermenu. 
Si povrebbe modificare il codice in modo da non caricare la voce di menu D /A (separatore) se ha impostato la classe u-hidden, ma francamente non so che controindicazioni potrebbe avere.

**Comment by raffaeleletizia** [comment]
Buonasera, guardate che nel burgermenu anche effettuando la modifica come  da voi indicata, non viene visualizzato i sottomenu indicati.

link:https://endometriosi.agenas.it

Possiamo effettuare qualcosa di diverso? 

joomla 3.10.3
versione ItaliaPA 3.9.0.20

**Comment by eshiol** [comment]
Bisogna creare due menu differenti. Uno per il megamenu ed uno per il burgermenu.
