### ISSUE TITLE
Link mancanti nelle intestazioni delle colonne del moduli menù posizione "Services"

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [retepasw/joomla-italiapa#427]
### Steps to reproduce the issue
Impostare il modulo come previsto dalla [Guida](https://paswjoomla.net/ItaliaPAsW/web-toolkit-styleguide/guida-template/costruire-la-homepage.html?start=6) 

### Actual result
Come osservabile nel [sito di esempio](https://paswjoomla.net/ItaliaPAsW/), sebbene il modulo realizzi  le colonne a partire dai componenti di un menù, la voce che dà l'intestazione della colonna del modulo (ad es. L'istituto) ha esteticamente l'aspetto di un link (underscore su hover, realizzato tramite css), ma non contiene un link. In particolare, non contiene il link della voce di menù da cui trae origine.

### Expected result
Mi aspetteri che l'intestazione recuperasse il link dal cui è generato. Citando il sito di esempio, mi asptterei che l'intestazione "L'istituto" puntasse alla [pagina linkata dal menù "La nostra Scuola" -> "Informazioni generali" -> "L'istituto"](https://paswjoomla.net/ItaliaPAsW/la-nostra-scuola/informazioni-generali/l-istituto.html).

**Comment by eshiol** [comment]
Non si riscontra alcun problema. Il comportamento è coerente con quanto atteso.
![image](https://user-images.githubusercontent.com/12718836/125657060-c84a42fd-36ce-4e98-b95a-110feaac2ea9.png)
Cliccando sul link L'istituto si viene reindirizzati alla pagina giusta.
![image](https://user-images.githubusercontent.com/12718836/125656297-141917cc-a67d-40bc-ba6b-810381c7bb64.png)
Per visualizzare per visualizzare La nostra scuola nel breadcrumb bisogna cambiare il tipo di voce di menu da Titolo separatore a URL # come avviene per la voce di menu Informazioni Generali.
![image](https://user-images.githubusercontent.com/12718836/125656555-76e8a10b-f768-40eb-a0e3-9f48f56314da.png)
