### ISSUE TITLE
glitch nella visualizzazione pagina con tabella in Chrome 

### ISSUE THREAD

**Issue by NioBee** [retepasw/joomla-italiapa#428]
Nelle pagine destinate alla descrizione dei singoli plessi compaiono delle linee grigie che attraversano il testo.
![image](https://user-images.githubusercontent.com/41695549/125311666-dc12f800-e333-11eb-92fe-6951faed286c.png)
Questo errore di visualizzazione non si presenta con firefox o edge.
Dopo qualche tentativo ho concluso che la causa risiede nella presenza nella pagina di una tabella nascosta con accordion. 
(avevo provato anche disabilitando i moduli in posizione right e le icone font awesome ma l'errore restava visibile)

### Expected result
![image](https://user-images.githubusercontent.com/41695549/125314051-239a8380-e336-11eb-955f-0698bdb6b084.png)

### System information (as much as possible)
Template v.3.9.0.20
Chrome v.91.0.4472.124 (64 bit)
Una pagina d'esempio che presenta l'errore: https://scuolesogliano.edu.it/secondaria-sogliano

**Comment by eshiol** [comment]
Proviamo ad aggiungere questo codice css nel file user.css
```
.fr-accordion--is-ready .fr-accordion__panel {
    overflow: hidden;
}
```

**Comment by atodaro** [comment]
Confermo che il codice proposto corregge il problema.

**Comment by eshiol** [comment]
Bisogna investigare sulla possibilità che generi altri problemi.

**Comment by eshiol** [comment]
È ancora presente il problema?
