### ISSUE TITLE
Caricamento allegati sulle pagine

### ISSUE THREAD

**Issue by ellegi178** [retepasw/joomla-italiapa#43]
### Steps to reproduce the issue
Non  riesco a trovare il modo di attivare funzionalità che consentano a redattori principianti, senza conoscenze tecniche, la possibilità di caricare allegati in maniera veloce e intuitiva, in modo che gli utenti possano scaricarli cliccando sui link di download sulle pagine.

### Expected result
Poter attivare tali funzionalità, possibilmente senza dover installare ulteriori componenti come _Public Competition_. 

### Actual result
Al momento non ho trovato altri modi che caricare l'allegato come media e poi inserire a mano il percorso in un link inserito sulla pagina.

### Additional comments
Mi rendo conto che forse sono io che non ho trovato la procedura giusta. Nel caso qualcuno sa indicarmi se ci sia e quale sia il luogo più appropriato per esprimere esigenze come questa? Grazie.

**Comment by atodaro** [comment]
Non è una peculiarità del template ma puoi utilizzare il componente "[attachment](https://extensions.joomla.org/extension/attachments/)" per allegare files agli articoli; unico problema che, seppure settati su "registered", i file restano accessibili anche se non visibili agli utenti "public"

**Comment by ellegi178** [comment]
Il componente fa benissimo quello di cui avevo bisogno.

Grazie della segnalazione
