### ISSUE TITLE
Abbellimento template

### ISSUE THREAD

**Issue by Jacopo71** [retepasw/joomla-italiapa#433]
Buongiorno.
Avrei bisogno di una informazione. Probabilmente non è il posto giusto per chiederla, ma non saprei come contattarvi.
L'anno scorso avete dato un codice da inserire nel template per abbellire il sito con l'effetto neve. Poiché non l'ho salvato o l'ho perso chissà dove, è possibile averlo nuovamente?

Vi ringrazio anticipatamente e buone feste

Jacopo

**Comment by atodaro** [comment]
Creare un nuovo file all'interno della cartella "js" del template; nomina il file "user.js" e incolla dentro il testo riportato nel file allegato.
[userjs.txt](https://github.com/retepasw/joomla-italiapa/files/7740555/userjs.txt)

**Comment by Jacopo71** [comment]
Grazie mille!

Ciao

Jacopo
