### ISSUE TITLE
File residui rimasti dopo aggiornamento ultima versione

### ISSUE THREAD

**Issue by vittorioalfieri** [retepasw/joomla-italiapa#443]
Successivamente all'aggiornamento alla versione 3.9 RC2 mi sono accorto facendo una differenza tra versione installa e nuovo pacchetto avevo nella mia installazione dei file non più presenti nel pacchetto, i file sono:
css\custom.css
html\com_content\category\news.php
html\com_content\category\news.xml
html\com_content\category\news_item.php
html\com_content\featured\default.xml
html\layouts\com_contact\field\render.php
html\layouts\com_contact\fields\render.php
html\mod_menu\socials_url.php

sentito Helios Ciancio mi ha detto che i seguenti file si possono eliminare non più usati:
css\custom.css
html\layouts\com_contact\field\render.php
html\layouts\com_contact\fields\render.php
html\mod_menu\socials_url.php

mentre per i file seguenti ne deve essere approfondito il contenuto:
html\com_content\category\news.php
html\com_content\category\news.xml
html\com_content\category\news_item.php

Si allega file zip contenente i file citati.

[html-com_content-category.zip](https://github.com/retepasw/joomla-italiapa/files/7904577/html-com_content-category.zip)

**Comment by eshiol** [comment]
Confermo che tutti i file indicati vanno cancellati.
