### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by sroselli** [retepasw/joomla-italiapa#445]
Una domanda, questo Template non è contemplato per Wordpress?

**Comment by atodaro** [comment]
No, per WordPress sono stati realizzati altri template tra i quali questo
https://github.com/italia/design-wordpress-theme

**Comment by sroselli** [comment]
Grazie lo valuto

Il Sab 19 Feb 2022, 11:48 Antonio Todaro ***@***.***> ha
scritto:
