### ISSUE TITLE
Leads Utilità

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#447]
### Steps to reproduce the issue

- Creare 1 nuovo Menu
- Creare 5 o 7 o 11 voci di Menu di tipo URL
- Creare 1 Modulo di tipo Menu (seleziona il menu creato precedentemente)
- - Nel tab Avanzate impostare il layout Lead

### Expected result

Visualizzazione di 5 / 7 / 11 voci di menu in una riga.

### Actual result

Il template attualmente posiziona le voci di menu in una colonna.

![Liceo Classico - Scienze Umane - Musicale - I I S   Napoleone Colajanni  Enna (1)](https://user-images.githubusercontent.com/24791536/155937384-83f831b2-923e-483f-9384-af83688643b2.png)

### System information (as much as possible)

ItaliaPa - 3.9.0.22-dev

**Comment by eshiol** [comment]
Si conferma l'anomalia, ma per 7, 9 e 11 elementi, per la mancanza delle seguenti classi
u-size1of7
u-sm-size1of7
u-md-size1of7
u-lg-size1of7
u-size1of9
u-sm-size1of9
u-md-size1of9
u-lg-size1of9
u-size1of11
u-sm-size1of11
u-md-size1of11
u-lg-size1of11

**Comment by eshiol** [comment]
[SUIT CSS utilities: size](https://github.com/suitcss/utils-size) supporta le classi u-sizeXofY con X minore di Y e Y = 2, 3, 4, 5, 6, 8, 10, 12.
Non si tratta di un bug ma di un caratteristica del web toolkit.
