### ISSUE TITLE
Lista di singola categoria

### ISSUE THREAD

**Issue by rosariogithub** [retepasw/joomla-italiapa#45]
### Comportamento anomalo
su lista di singola categoria quando si passa su "Titolo" su "Data pubblicazione" su "Visite" la descrizione viene sparata a sinistra

### System information (as much as possible)

![image](https://user-images.githubusercontent.com/34281129/33620942-99bf0cde-d9e9-11e7-8546-e23c1e3d2cf0.png)

**Comment by rosariogithub** [comment]
su lista di singola categoria quando si passa su "Titolo" su "Data pubblicazione" su "Visite" la descrizione viene sparata a sinistra

**Comment by atodaro** [comment]
Vedi issue #34
