### ISSUE TITLE
Form di registrazione

### ISSUE THREAD

**Issue by vespuccicolombo** [retepasw/joomla-italiapa#453]
### Steps to reproduce the issue
Voglio creare una nuova voce di menu che punti a un Form di registrazione. Procedo così:
**Nuova Voce di Menu -> Tipo voce di menu -> Utenti -> Modulo di registrazione**

### Expected result
![image](https://user-images.githubusercontent.com/101291789/157531190-3d413443-ea4f-47f1-a0d5-c5363cc6f9bc.png)

IMMAGINE RELATIVA A SITO NON ITALIAPA. Mostra comunque quello che mi aspetto di vedere (grafica a parte) se il tipo Voce di menu - Utenti fosse effettivamente un modulo di registrazione.

### Actual result
![image](https://user-images.githubusercontent.com/101291789/157531320-5ab8b97a-99de-446c-a49d-0da5fe39e3f4.png)
**Anziché visualizzare il form per la registrazione, mostra il modulo di login!** 

### System information (as much as possible)
Joomla! 3.10.6 Stable [ Daraja ] 12-February-2022 
PHP Version 7.4.24

**Comment by Knock-Out** [comment]
### **Devi abilitare la registrazione utenti**

![Registrazione - I I S   Napoleone Colajanni  Enna](https://user-images.githubusercontent.com/24791536/157598827-197c2c40-63aa-49e3-84f5-8a3d4168b089.png)

![Registrazione - I I S   Napoleone Colajanni  Enna (1)](https://user-images.githubusercontent.com/24791536/157599017-27e1cd73-a657-4fee-9685-d83a06a9428b.png)

**Comment by vespuccicolombo** [comment]
Grazie mille, non ci avevo pensato...

Il gio 10 mar 2022, 06:59 Claudio Rosselli ***@***.***> ha
scritto:
