### ISSUE TITLE
Content - Page Break for ItaliaPA | Layout Tabs

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#458]
### Steps to reproduce the issue

**Plugin**

- Disabilitare: Content - Pagebreak
- Abilitare:  Content - Page Break for ItaliaPA

**Contenuti >> Articoli**

- Crea nuovo articolo
- Inserisci l'interruzione di pagina con l'utilizzo del pulsante Pagebreak che si trova nella parte inferiore del testo di un articolo. 

1. Questo plugin consente la creazione di un articolo impaginato con una tabella dei contenuti.
2. Il Pagebreak verrà visualizzato nella finestra del testo come una singola linea orizzontale.
3. Il testo visualizzato dipenderà dalle opzioni scelte, cioè il titolo, il testo alternativo (se fornito) o i numeri di pagina.

Selezionare il TAB >> Campi aggiuntivi
Impostare >> Pagebreak >> Tabs

### Expected result

**Mi aspetto che non ci siano errori di visualizzazione**

### Actual result

Notice: Undefined index: active in 

- /templates/italiapa/src/html/iwt.php on line 159

Notice: Undefined index: article-23 in 

- /templates/italiapa/src/html/iwt.php on line 204

Notice: Trying to access array offset on value of type null in 

- /templates/italiapa/src/html/iwt.php on line 204

Notice: Undefined index: article-23 in 

- /templates/italiapa/src/html/iwt.php on line 226

Notice: Trying to access array offset on value of type null in 

- /templates/italiapa/src/html/iwt.php on line 226

Notice: Undefined index: article-23 in 

- /templates/italiapa/src/html/iwt.php on line 204

Notice: Trying to access array offset on value of type null in 

- /templates/italiapa/src/html/iwt.php on line 204

Notice: Undefined index: article-23 in 

- /templates/italiapa/src/html/iwt.php on line 226

Notice: Trying to access array offset on value of type null in 

- /templates/italiapa/src/html/iwt.php on line 226

Notice: Undefined index: article-23 in 

- /templates/italiapa/src/html/iwt.php on line 204

Notice: Trying to access array offset on value of type null in 

- /templates/italiapa/src/html/iwt.php on line 204

Notice: Undefined index: article-23 in 

- /templates/italiapa/src/html/iwt.php on line 226

Notice: Trying to access array offset on value of type null in 

- /templates/italiapa/src/html/iwt.php on line 226

![Organigramma - I I S   Napoleone Colajanni  Enna](https://user-images.githubusercontent.com/24791536/158845433-e382a355-aad6-4657-b440-d256d0c56ed7.png)

### System information (as much as possible)

Joomla! 3.10.6
pkg_italiapa-3.9.0.22-dev-48911923892164e88b80f3f0b5a8f67df19ca9d0

### Additional comments

**Tabs funzionanti**

![Cattura](https://user-images.githubusercontent.com/24791536/158847354-5f6b8926-043c-4a45-8c1c-4af81a9780c0.JPG)

**Comment by eshiol** [comment]
Problema confermato
