### ISSUE TITLE
Adattamento pagina mobile 

### ISSUE THREAD

**Issue by raffaeleletizia** [retepasw/joomla-italiapa#459]
Buongiorno,
facendo riferimento ai link sottostanti
https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/cose-endometriosi
https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/i-sintomi
https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/la-diagnosi
https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/le-cure
https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/i-rischi-le-avvertenze
https://endometriosi.agenas.it/index.php/home/view1/team-progetto

in modalita mobile viene spaginata e quindi non visibile correttamente. Come posso migliorare tale condizione?

Grazie come sempre

**Comment by eshiol** [comment]
Gentile Raffaele Letizia,
il canale github non è il luogo dove viene fornita assistenza alla realizzazione di siti web, ma il luogo dove condividere lo sviluppo del template ItaliaPA.
Per assistenza può utilizzare il link della comunità di pratica Porte Aperte sul Web, ben visibile in basso a sinistra nel template utilizzato anche sul sito web da lei indicato.

**Comment by Knock-Out** [comment]
@raffaeleletizia 

> Buongiorno, facendo riferimento ai link sottostanti https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/cose-endometriosi https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/i-sintomi https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/la-diagnosi https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/le-cure https://endometriosi.agenas.it/index.php/endometriosi-home/seppat/i-rischi-le-avvertenze https://endometriosi.agenas.it/index.php/home/view1/team-progetto
> 
> in modalita mobile viene spaginata e quindi non visibile correttamente. Come posso migliorare tale condizione?
> 
> Grazie come sempre

**E molto probabile che tu abbia all'interno delle tabelle / elementi markup non compatibili.**
