### ISSUE TITLE
Colore categoria a scarso contrasto in layout "Categoria Blog"

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#46]
### Steps to reproduce the issue
creo una voce di menù del tipo "categoria blog" e nella tab "opzioni" alla voce "categoria" seleziono il parametro "mostra"

### Expected result
In frontend, il nome della categoria, posto sopra i dettagli dell'articolo, è di colore nero o, comunque, ad elevato contrasto rispetto allo sfondo.
### Actual result
Il colore del nome della categoria è grigio e a scarso contrasto con il background.
![screenshot-paswjoomla net-2017-12-08-21-59-50-755](https://user-images.githubusercontent.com/12257435/33784950-2b068c00-dc63-11e7-8e9f-072704129428.png)

### System information (as much as possible)
Joomla! 3.8.2 
ItaliaPA 3.8.0.3

### Additional comments
Questo comportamento si manifesta anche negli altri tipi di layout di categoria blog: focus, grid, masonry ad eccezione del "news"

**Comment by eshiol** [comment]
problema non presente nella 3.8.0.15
