### ISSUE TITLE
Articoli - Tooltip Stampa

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#463]
### Steps to reproduce the issue

**Beckend** >> Configurzione Globale

- Articoli

**Tab Articoli**

- Impostare la funzione Stampa in **Mostra** 

**Mostra o nascondi il pulsante Stampa. Questo consente di stampare un articolo.**

### Expected result

No notice

### Actual result

Notice: Undefined variable: legacy in ../templates/italiapa/html/com_content/article/default.php on line 110

![Circolari per i genitori  2  - I I S   Napoleone Colajanni  Enna (1)](https://user-images.githubusercontent.com/24791536/159647186-ea8d2fdf-f350-4a3c-820b-e0167de136f9.png)

### System information (as much as possible)

Joomla! 3.10.6
pkg_italiapa-3.9.0.22-dev-48911923892164e88b80f3f0b5a8f67df19ca9d0

### Additional comments

![Circolari per i genitori  2  - I I S   Napoleone Colajanni  Enna](https://user-images.githubusercontent.com/24791536/159646686-5be0cb5b-6140-4d9e-91e5-b4e5d1ecdf4f.png)

**Comment by Knock-Out** [comment]
### Additional system information

- **PHP 7.4 o 8.0**

**Comment by eshiol** [comment]
L'errore si presenta nella pagina di anteprima.
