### ISSUE TITLE
Modulo Personalizzato - Stile del modulo lg

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#466]
### Steps to reproduce the issue

- crea modulo personalizzato
- Inserisci del contenuto
- posizione: featured
- stile del modulo: lg

### Expected result

-

### Actual result

Notice: Undefined variable: moduleClass1 in /var/www/.../.../.../templates/italiapa/html/modules.php on line 110

![error](https://user-images.githubusercontent.com/24791536/169110685-301d8378-2e35-4e1b-b674-a522c36c52b8.png)

### System information (as much as possible)

Joomla! 3.10.9
ItaliaPA - 3.9.0.22-dev

**Comment by eshiol** [comment]
Il bug non riguarda il modulo Personalizzato, ma la posizione Featured.
