### ISSUE TITLE
Modulo contatti

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#47]
### Steps to reproduce the issue
Creo un contatto con il componente nativo Joomla! e una voce di menù ad esso collegato

### Expected result
La pagina "contatto" presenta una formattazione del tipo:
[Formtpl default](https://italia.github.io/design-web-toolkit/components/preview/formtpl--default.html)

### Actual result
Il modulo non ha ancora una specifica formattazione: occorre procedere all'override del modulo

**Comment by Knock-Out** [comment]
[Pull-35](https://github.com/retepasw/joomla-italiapa/pull/35) <p>Ho testato questa richiesta <g-emoji alias="white_check_mark" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/2705.png" ios-version="6.0">✅</g-emoji> con successo <a href="https://github.com/retepasw/joomla-italiapa/commit/ca69edf1d745477ed2fdcf2554ea93a9fdfb2719"><tt>ca69edf</tt></a></p>

**Comment by atodaro** [comment]
Esempio di layout modulo contatti

![modulo contatti](https://user-images.githubusercontent.com/12257435/34908115-fb299cae-f88a-11e7-95f4-fc2e5e3bcad1.png)

**Comment by Knock-Out** [comment]
Attivato reCAPTCHA. Funziona perfettamente.

![cattura](https://user-images.githubusercontent.com/24791536/35147763-0b8997d2-fd10-11e7-8401-e11ac44f3c9b.PNG)

**Comment by eshiol** [comment]
#134

**Comment by eshiol** [comment]
non presente 3.8.0.15
