### ISSUE TITLE
Errore in aggiornamento da 3.9 alpha 16 a 3.10

### ISSUE THREAD

**Issue by Tonycel64** [retepasw/joomla-italiapa#474]
Forse sono nel posto sbagliato... comunque da insegnante gestisco il sito del mio liceo con il template ItaliaPA, ma dopo la 3.9 alpha16 non riesco più ad aggiornare, se carico le versioni successive si vede solo la barra del Main Menù e niente altro. Attualmente ho installato Joomla 3.10. Grazie se potete aiutarmi

**Comment by eshiol** [comment]
Buongiorno Tonycel64. Sei nel posto sbagliato ed hai usato un modo sbagliato per aprire una issue.

Per supporto su problemi legati al singolo sito web ti invito ad utilizzare uno dei seguenti canali
https://www.facebook.com/groups/pasw4joomla
https://www.paswjoomla.net/joomla/forum/template-italiapa.html
https://forum.joomla.it/index.php/board,97.0.html
