### ISSUE TITLE
Bug Immagine Responsive all'interno degli articoli

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#475]
### Steps to reproduce the issue
Creo un articolo con editor tiny mce; all'interno dell'articolo inserisco una immagine giustificata tramite pulsante giustifica di tinyMCE

### Expected result

L'immagine è centrata e viene ridimensionata al cambio di dimensione della finestra. (Vedi [issue ](https://github.com/retepasw/joomla-italiapa/pull/72)

### Actual result

L'immagine non è responsive.

### System information (as much as possible)
Joomla 3.10.11
ItaliaPA 3.10

### Additional comments
Prima dell'installazione di ItaliaPA 3.10 le immagini all'interno degli articoli erano responsive.
Avevo anche aggiunto un codice personalizzato del CSS:

*/Immagini responsive*/
[itemprop="articleBody"] img {
	max-width: 100%;
	height: auto;
}

Ho effettuato le prove sia con css personalizzato che senza: le immagini continuano a non essere ridimensionate.

**Comment by eshiol** [comment]
Confermo la regressione a partire dalla versione alpha 12.
