### ISSUE TITLE
Articoli in evidenza di tutte le categorie (layout: Hero news)

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#48]
![screencapture-scuola-iamawebmaster-com-1512979962461](https://user-images.githubusercontent.com/24791536/33821256-7c742fb0-de53-11e7-8021-021fb56e5a8d.png)
### Steps to reproduce the issue

Articoli in evidenza di tutte le categorie (layout: Hero news)

### Expected result

Visualizzazione Hero

### Actual result

0
Call to a member function get() on null
Non è possibile visualizzare questa pagina, potrebbe essere a causa di:

un
bookmark/preferiti scaduto
una ricerca attraverso il motore di ricerca che ha una
indicizzazione non aggiornata di questo sito
un
indirizzo compilato male
non hai accesso
a questa pagina
la risorsa richiesta non esiste.
si è verificato un errore durante l'esecuzione della richiesta.

**Comment by Knock-Out** [comment]
Se non ci sono articoli in evidenza, la visualizzazione Hero News presenta l'errore come sopra.

**Comment by eshiol** [comment]
problema non riscontrato nella versione 3.8.0.5
