### ISSUE TITLE
Menù Treeview: visualizzazione "closed" delle sottovoci di menù

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#51]
### Steps to reproduce the issue
Genero un modulo menù in posizione right con layout treeview.

### Expected results
L'albero di visualizzazione mostra solo il livello principale mentre per accedere alle sottovoci si deve cliccare sull'icona "freccia in basso" o "segno più" (solo se treeview impostato su "treeview plus"

### Actual result
Le sottovoci di menù sono sempre visibili, sia nel modulo menù right che nel modulo burger del megamenù in modalità mobile.
### System information (as much as possible)
ItaliaPA 3.8.0.3

### Additional comments
_Su sito demo il problema al momento è stato risolto agendo sul codice php_

**Comment by eshiol** [comment]
Vedi PR #40
