### ISSUE TITLE
posizione moduli homepage

### ISSUE THREAD

**Issue by ellegi178** [retepasw/joomla-italiapa#52]
### Steps to reproduce the issue
Vorrei posizionare i diversi moduli dell’homepage, come presenti nel modello di sito fornito da design.italia, ma non riesco a utilizzare le posizioni del template;
Ad esempio per inserire la grande notizia in apertura che vedete nel print screen che allego mi viene da procare a usare la posizione _lead_.
![posizione_lead](https://user-images.githubusercontent.com/33519380/33979361-48958bdc-e0a4-11e7-8094-7884ac236edf.jpg)

### Expected result
Mi aspetterei che un elemento inserito nella posizione _Lead_,venisse visualizzato in alto nella pagina,  anche in base a quello che mi sembra suggerisca il nome dell’etichetta, o la dimensione del carattere (grande, da titolo di testa).

### Actual result
e invece quello che associo alla posizione lead, mi appare in ultima posizione fondo alla pagina.

### Additional comments
Grazie

**Comment by eshiol** [comment]
Secondo le linee guida il lead è il menu che precede il footer
![image](https://user-images.githubusercontent.com/12718836/34992348-35817950-facd-11e7-805a-e45d1d9f91bf.png)
[https://italia.github.io/design-web-toolkit/components/preview/comuni.html](url)
