### ISSUE TITLE
Immagine di menu

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#55]
### Steps to reproduce the issue

Modulo "menu" - posizione "featured" - layout "entrypoint".

![cattura](https://user-images.githubusercontent.com/24791536/34405779-86098204-ebb5-11e7-8134-36a0119bae61.PNG)

Voce di menu >> Tab Opzioni link >> Immagine menu - - Non è responsive

### Actual result

![cattura1](https://user-images.githubusercontent.com/24791536/34405899-26dcc9e8-ebb6-11e7-900f-2217531ccae0.PNG)

**Comment by eshiol** [comment]
problema non riscontrato.

**Comment by Knock-Out** [comment]
Il problema si verifica se inserisco una classe nella voce di menu. 
Nel mio caso vorrei centrare l'immagine perché da monitor è decentrata. 

![cattura](https://user-images.githubusercontent.com/24791536/35145550-82519228-fd08-11e7-8e7c-995680176749.PNG)

La classe che ho utilizzato è questa.

u-textClean u-text-h3 u-color-white Color u-padding-left-none u-margin-all-l u-borderRadius-xxs

**Comment by eshiol** [comment]
Nel caso l'immagine sia più grande del tile si può aggiungere la classe u-sizeFull all'immagine
![italiapa0023](https://user-images.githubusercontent.com/12718836/36759336-490e2f5c-1c17-11e8-9b3a-25d4a113817a.png)

**Comment by Knock-Out** [comment]
Classe applicata con successo.
