### ISSUE TITLE
Lista di singola categoria - layout lista delle sottocategorie

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#56]
### Steps to reproduce the issue

Menu voce lista singola categoria >> Impostazione >> Tab Categoria

Mostra testo Sottocategorie

![cattura](https://user-images.githubusercontent.com/24791536/35227621-d8e2258e-ff8e-11e7-855b-d3478cd57a50.PNG)

La lista delle sotto categorie non ha un layout

### Expected result

![1cattura](https://user-images.githubusercontent.com/24791536/34579335-d543de22-f188-11e7-9564-042fdd647178.PNG)

### Actual result

![cattura1](https://user-images.githubusercontent.com/24791536/35227662-f0bc8cbc-ff8e-11e7-929b-9c5dd7c1ce94.PNG)

### System information (as much as possible)

Joomla 3.8.3
ItaliaPA 3.8.0.4

**Comment by Knock-Out** [comment]
Sarebbe opportuno integrare questo tipo di visualizzazione.

https://italia.github.io/design-web-toolkit/components/detail/page--landing.html

**Comment by eshiol** [comment]
https://italia.github.io/design-web-toolkit/components/detail/listing--default.html
