### ISSUE TITLE
Layout "Hero news": richiesta per nuova funzionalità

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#57]
### Steps to reproduce the issue
Creo un articolo per una sezione tematica con immagine di introduzione

### Expected result
Voglio assegnare il tipo di layout "hero news" come attualmente posso fare per la tipologia di articoli in evidenza nella home page

### Actual result
Il layout non è disponibile per articoli che non siano in evidenza.

### System information (as much as possible)
Template ver. Alpha 3

**Comment by Knock-Out** [comment]
Layout Heroes - News: rilevato bug
Pagina bianca con scelta specifica di una o più categorie.

Titolo voce di menu * Layout: Heroes - News
TAB Layout >> Seleziona categorie

**Comment by Knock-Out** [comment]
Questa Issue ha un nesso con >> PR #358 (Closed)
