### ISSUE TITLE
Layout system-pagebreak

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#63]
### Steps to reproduce the issue

Layout system-pagebreak

### Expected result

https://italia.github.io/design-web-toolkit/components/preview/listing--default.html

![cattura](https://user-images.githubusercontent.com/24791536/34908551-be5976d0-f891-11e7-9d9a-12279ff5337b.PNG)

### Actual result

![cattura](https://user-images.githubusercontent.com/24791536/34908515-20bf8720-f891-11e7-9c09-b4b3b0053d2e.PNG)

### System information (as much as possible)

3.8.0.3

**Comment by eshiol** [comment]
Mancano i passi per riprodurre il problema

**Comment by Knock-Out** [comment]
Il toc (table of content) che crea in automatico Joomla! non è formattato secondo il layout che ho segnalato.

**Comment by eshiol** [comment]
Si deve riscrivere il plugin content - pagebreak, non è possibile risolvere con un override del template.

**Comment by eshiol** [comment]
https://paswjoomla.net/ItaliaPAsW/web-toolkit-styleguide/components/suit-css
si accettano commenti

**Comment by Knock-Out** [comment]
Ottimo

**Comment by eshiol** [comment]
vedere PR #67
