### ISSUE TITLE
Modifica articolo da frontend con firefox

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#65]
### Steps to reproduce the issue
Accedo al sito come utente registrato e clicco sul pulsante di modifica di un qualsiasi articolo utilizzando il browser firefox

### Expected result
Dopo aver effettuato l'accesso, sono riconosciuto come utente registrato con permessi di modifica degli articoli e si apre la pagina di modifica del contenuto degli articoli

### Actual result
Dopo aver effettuato l'accesso, sono riconosciuto come utente registrato con permessi di modifica degli articoli ma con firefox il pulsante "modifica articolo" non è attivo e non si riesce ad accedere all'editor di testo

### System information (as much as possible)
ItaliaPA 3.8.0.3

### Additional comments
Il problema con firefox si manifesta anche con gli altri buttons per email e stampa dell'articolo

**Comment by eshiol** [comment]
Con firefox non funziona nessun pulsante.
