### ISSUE TITLE
Pulsante "email" articolo da frontend: creazione layout 

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#70]
### Steps to reproduce the issue
Accedo da frontend ad un articolo e clicco sul pulsante "email" per poter inviare il testo dell'articolo tramite email

### Expected result
Si apre una finestra di popup con che consente di inserire le informazioni per l'invio tramite email dell'articolo come nell'esempio riportato in immagine
![screen email1](https://user-images.githubusercontent.com/12257435/35064799-82b42926-fbcb-11e7-96ca-1724f3300d96.png)

### Actual result
Al momento, dopo aver cliccato sul pulsante email, la finestra popup che si apre non presenta alcuna formattazione relativa alle linee guida.
![screen email2](https://user-images.githubusercontent.com/12257435/35064910-cef3fc58-fbcb-11e7-8317-9fee3b4537e5.png)

### System information (as much as possible)
ItaliaPA 3.8.0.3

### Additional comments
Layout di riferimento dal webtoolkit: vedi al seguente link solo per le voci necessarie
https://italia.github.io/design-web-toolkit/components/preview/formtpl--example.html

**Comment by eshiol** [comment]
e se il pulsante email lo mettessimo nel pulsante condividi?
![image](https://user-images.githubusercontent.com/12718836/35139979-bd34b680-fcf5-11e7-8496-e328821823b0.png)
![image](https://user-images.githubusercontent.com/12718836/35139957-aadb8e50-fcf5-11e7-940c-ee73fd5e1c16.png)

**Comment by atodaro** [comment]
La soluzione è funzionale; potrebbe essere utile inserire anche il pulsante stampa
