### ISSUE TITLE
Nuovo Layout da implementare: popup inserimento immagini in articolo da frontend con TinyMCE

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#76]
### Steps to reproduce the issue
Creo un articolo da frontend e provo a inserire un'immagine dalla cartella immagini, compreso l'upload del file da locale a remoto. Si apre la finestra di popup di tinymce per accedere alle funzionalità di caricamento immagini e successivo inserimento.
### Expected result
La finestra popup per la selezione dell'immagine ha un layout in linea con quanto previsto dal toolkit
### Actual result
La finestra popup non ha il layout con la formattazione corretta. Vedi screenshot
![screenshot-paswjoomla net-2018-01-19-18-00-00-715](https://user-images.githubusercontent.com/12257435/35162139-a4583e0a-fd42-11e7-8c42-d4a61ccd5a71.png)

### System information (as much as possible)
ItaliaPA alpha 3.8.0.3

**Comment by atodaro** [comment]
La mancanza di layout è relativa all'inserimento di tutte le funzionalità che consentono di inserire i diversi elementi in un articolo da front end: link, moduli, immagini, riferimenti ad altri articoli

**Comment by eshiol** [comment]
Comportamento corretto con PR #193
