### ISSUE TITLE
Voci menu scompaiono

### ISSUE THREAD

**Issue by tnuukav** [retepasw/joomla-italiapa#80]
### Steps to reproduce the issue
Il problema è un po' casuale, comunque riesco a riprodurlo più regolarmente su un tablet, passando da modo portrait a landscape varie volte e navigando con altre schede.
(Problema riproducibile, si veda aggiornamento in basso)

### Expected result
Il menù principale dovrebbe presentare sempre tutte le voci, anche dopo aver navigato su altre schede.

### Actual result
Quando si torna sulla scheda, il menu ha "perso" delle voci (quelle che non hanno sottovoci) e le frecce per accedere ai sottomenu, come da immagini.

![image](https://user-images.githubusercontent.com/35748251/37313511-d4c6565e-264f-11e8-868d-e3de92a06277.png)

![image](https://user-images.githubusercontent.com/35748251/37313525-ee435a00-264f-11e8-9ae8-bd2726ae9a68.png)

### System information (as much as possible)
Errore riprodotto con chrome e puffin, da pc e tablet.
Joomla 3.8.3 installazione da ergonet+aggiornamento
Php 7.0.14 su linux
Versione template: 3.8.0 alpha 3

### Additional comments
Trovato inizialmente su sito in costruzione, accessibile solo dopo login.

Ora testato anche sul demo: https://paswjoomla.net/ItaliaPAsW/
Riproducibile anche su: https://antoniotodaro.it/verdellinopa - http://www.liceodavincifloridia.gov.it - https://www.sturzobiancavilla.gov.it/ - https://www.liceorummo.gov.it

**Comment by eshiol** [comment]
Impossibile confermare l'anomalia. Se non vengono forniti dettagli volti a riprodurre il problema, questa issue verrà chiusa.

**Comment by tnuukav** [comment]
Purtroppo, come scritto, il problema sembra essere abbastanza casuale, non è riproducibile in modo sistematico.
Se dovessi trovare un modo per renderlo riproducibile aggiornerò la questione.

Grazie

**Comment by tnuukav** [comment]
Ho trovato il modo di riprodurre sistematicamente il problema:
- caricare una pagina in modo che il menù sia visualizzato come menù hamburger
- aprire il menù hamburger e cambiare pagina
- aumentare le dimensioni della finestra (per esempio ruotando un tablet) 

Testato anche sul demo: https://paswjoomla.net/ItaliaPAsW/
Riproducibile anche su: https://antoniotodaro.it/verdellinopa - http://www.liceodavincifloridia.gov.it

Scompaiono le frecce accanto alle voci di menu e anche le voci che non hanno sottovoci ad esempio i pulsanti "ACCEDI" o la voce "Home" sui siti citati qui sopra...

**Comment by eshiol** [comment]
problema confermato
