### ISSUE TITLE
Modulo schema.org

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#81]
### Steps to reproduce the issue

Contenuto in due righe successive [immagine demo, Modulo schema.org >> URP]

### Expected result

Layout contenuto in una riga [come immagine demo, Modulo custom >> Codici istituzionali]

### Actual result

![cattura](https://user-images.githubusercontent.com/24791536/35621611-43609a4c-0685-11e8-81b8-2a09b0137447.PNG)

### System information (as much as possible)

Joomla 3.8.4
ItaliaPA version 3.8.0.4

**Comment by eshiol** [comment]
applicare PR #116 ed aggiungere i seguenti stili css
```
.Footer-subBlock address.address h3{display:inline}
.Footer-subBlock address.address h3:before{content:'';display:block}
.Footer-subBlock address.address h3:after{content:' '}
```
