### ISSUE TITLE
Posizione footer

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#83]
### Steps to reproduce the issue

Posizione footer >> Modulo custom
Non è presente un layout separatore, la linea orizzontale che separa il titolo con il contenuto

### Expected result

Con seperatore [come immagine demo, Modulo schema.org >> URP]

### Actual result

![cattura](https://user-images.githubusercontent.com/24791536/35622234-6087aa28-0687-11e8-8d54-55928faa91e2.PNG)

### System information (as much as possible)

Joomla 3.8.4
ItaliaPA version 3.8.0.4

**Comment by eshiol** [comment]
Prova ad impostare il campo Suffisso classe CSS modulo con la seguente stringa senza apici ' Footer-subBlock'; è importante lo spazio iniziale.

**Comment by Knock-Out** [comment]
Si comporta in modo diverso

![cattura](https://user-images.githubusercontent.com/24791536/35663657-a0b8a02e-071e-11e8-8bc1-0a36b59d1dd2.PNG)

![cattura](https://user-images.githubusercontent.com/24791536/35663620-75a115f6-071e-11e8-8683-ec1515598745.PNG)
