### ISSUE TITLE
Editor Jce

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#84]
### Steps to reproduce the issue

Front-end  >> Modifica articolo
Subito dopo l'editor testo non esiste un layout per i buttons 

### Expected result

![3](https://user-images.githubusercontent.com/24791536/35622840-97254be2-0689-11e8-91ed-1f89005884a4.PNG)

### Actual result

![1](https://user-images.githubusercontent.com/24791536/35622776-55aeecea-0689-11e8-971e-46968414e8bc.PNG)

![2](https://user-images.githubusercontent.com/24791536/35622785-5ae10496-0689-11e8-9f25-28722c629b66.PNG)

### System information (as much as possible)

Joomla 3.8.4
ItaliaPA version 3.8.0.4

**Comment by eshiol** [comment]
#277 #278
