### ISSUE TITLE
Category blog (News): richiesta integrazione

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#9]
### Steps to reproduce the issue
Creo una voce di menù con vista category blog - news, con articoli senza immagine introduttiva.

### Expected result
Gli articoli senza immagine introduttiva sono visualizzati per l'intera larghezza della pagina e occupano anche la parte del placeholder.

### Actual result
Anche senza l'immagine l'articolo occupa solo la parte dedicata al testo
![per issue category blog](https://user-images.githubusercontent.com/12257435/32700818-bfc33f12-c7ca-11e7-9e96-5b556c61a02d.png)
Esempio al seguente link: 
[https://antoniotodaro.it/verdellinopa/aree-del-personale/docenti-e-ata/circolari-e-comunicazioni](url)
### System information (as much as possible)
Joomla! 3.8.2
ItaliaPA 3.8.0.1

**Comment by eshiol** [comment]
Nella versione 3.8.0.1 del template il layout Category blog (news) non è presente. Ti chiedo di inserire il commento nella PR #7  relativa al layout Category blog (News).
