### ISSUE TITLE
New feature: modulo "elenco articoli" con formattazione della posizione "services"

### ISSUE THREAD

**Issue by atodaro** [retepasw/joomla-italiapa#90]
### Steps to reproduce the issue
Creo un modulo "Elenco articoli" e assegno la posizione "services"; il titolo del modulo è settato su "mostra".

### Expected result
Il modulo, a seconda della posizione che occupa, ha il titolo formattato come nell'immagine sotto:
![screen 1](https://user-images.githubusercontent.com/12257435/35770555-e9257b9c-091d-11e8-86db-ce5fb67c17b9.png)

I titoli degli articoli sono link con formattazione come nell'immagine sotto:
![screen 2](https://user-images.githubusercontent.com/12257435/35770557-ed74d9cc-091d-11e8-90b9-bb3750a4aa06.png)

### Actual result
**Titolo e link non hanno formattazione:**
![screen 3](https://user-images.githubusercontent.com/12257435/35770565-16d8488a-091e-11e8-80a2-9e0148137a8d.png)

### System information (as much as possible)
Joomla! 3.8.4
ItaliaPA 3.8.0.5

### Additional comments
Funzionalità non ancora implementata per la quale è necessario un override del modulo "elenco articoli"

**Comment by Knock-Out** [comment]
Applicata patch con successo.

![cattura](https://user-images.githubusercontent.com/24791536/35795278-f1ddbcb8-0a58-11e8-8633-c27d16d3e4b8.PNG)
