### ISSUE TITLE
Layout Tags - etichetta mancante

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#94]
### Steps to reproduce the issue

Dopo aver creato e applicato dei tags, nell'articolo sono visibili ma no il titolo "Tags:" (circolare Genitori Alunni)

### Expected result

![cattura](https://user-images.githubusercontent.com/24791536/35819616-81573cd0-0aa3-11e8-9a13-c8180dadbc20.PNG)

### Actual result

![tag](https://user-images.githubusercontent.com/24791536/35803512-53700c68-0a74-11e8-9e5e-3a1da8b74681.PNG)

### System information (as much as possible)

Joomla! 3.8.4
ItaliaPA 3.8.0.5

### Additional comments

Anche nella pagina dell'articolo non è visibile il titolo "Tags:"

![cattura](https://user-images.githubusercontent.com/24791536/35819044-e17aef3c-0aa1-11e8-88d9-5f628ec5b122.PNG)

**Comment by atodaro** [comment]
Problema **non rilevato** nel sito demo ItaliaPAsW.
Ho creato un nuovo articolo, ho specificato i tag e da frontend, visualizzando l'articolo, si visualizza sia l'etichetta "tags" che le voci di tag inserite.
[link all'esempio](https://paswjoomla.net/ItaliaPAsW/aree-del-personale/docenti-e-ata/circolari-e-comunicazioni/2474-test-per-tag)

**Comment by atodaro** [comment]
Confermo che [nel sito di Claudio](https://www.sturzobiancavilla.gov.it/la-scuola/informazioni/bacheca-scolastica/11-non-una-volta-i-testi.html) **il tag inserito non è preceduto dall'etichetta tags**. 
Ho confrontato le opzioni di pubblicazione e sono le stesse del sito demo ItaliaPAsW

**Comment by eshiol** [comment]
comportamento confermato
