### ISSUE TITLE
Componente Tags - Layout Lista articoli

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#95]
### Steps to reproduce the issue

Non esiste un layout per la lista degli articoli collegata ad un determinato tags.

### Expected result

https://italia.github.io/design-web-toolkit/components/preview/listing--default.html

### Actual result

![tags1](https://user-images.githubusercontent.com/24791536/35803627-bd7c0daa-0a74-11e8-840a-e7ddcf9a9eb9.PNG)

### System information (as much as possible)

Joomla! 3.8.4
ItaliaPA 3.8.0.5

### Additional comments

Sarebbe utile implementare una lista che elenca i vari articoli attinenti a quel tag

**Comment by atodaro** [comment]
Parere condiviso: la lista degli articoli collegati ad una categoria di tag potrebbe avere il [layout ](https://italia.github.io/design-web-toolkit/components/preview/listing--default.html) indicato da Claudio.
