### ISSUE TITLE
Voce menu Categoria Blog - Data Creazione

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#97]
### Steps to reproduce the issue

Voce menu categoria Blog >>tab Opzioni >> data di pubblicazione "Mostra".

### Expected result

![hello2](https://user-images.githubusercontent.com/24791536/35963938-920e709c-0cb6-11e8-84eb-7b3181ad22bd.png)

### Actual result

Nella pagina Categoria Blog è visibile la data di pubblicazione della categoria (Creato 14 Gennaio 2014).
Questo è un comportamento anomalo perché solo l'articolo dovrebbe mostrare la data.

![hello](https://user-images.githubusercontent.com/24791536/35963812-42f0d2fc-0cb6-11e8-8617-f9ba3fde487d.png)

### System information (as much as possible)

Joomla! 3.8.4
ItaliaPA 3.8.0.5

### Additional comments

Voce menu categoria Blog >>tab Opzioni >> data di pubblicazione "Nascondi".
La data di pubblicazione della categorie non è visibile, ma in questo modo anche la data di pubblicazione dell'articolo è nascosta.

**Comment by atodaro** [comment]
#Risolto: la voce di menù che porta alla categoria deve essere settata dalla tab "opzioni", selezionando "nascondi" in data di pubblicazione.
![nascondi](https://user-images.githubusercontent.com/12257435/35967839-65d7d2f0-0cc2-11e8-96b1-1852f98eb9ff.png)
