### ISSUE TITLE
Modulo posizione featured >> layout "entrypoint"

### ISSUE THREAD

**Issue by Knock-Out** [retepasw/joomla-italiapa#98]
### Steps to reproduce the issue

Modulo tipo Menu >> posizione featured >> Layout "entrypoint"
Suffisso classe modulo >>  Color u-padding-all-xxl u-margin-all-s u-borderRadius-xxs u-background-40
Menu 
1 voci di menu separatore - due sotto voci di menu
1 voci di menu separatore - due sotto voci di menu

### Expected result

![f](https://user-images.githubusercontent.com/24791536/35968726-f6f4a540-0cc4-11e8-968f-f9d80052a508.png)

### Actual result

![27797939_10211193080598840_8482039626617899315_o](https://user-images.githubusercontent.com/24791536/35968752-06181e1c-0cc5-11e8-826e-90f824955f93.jpg)

### System information (as much as possible)

Joomla! 3.8.4
ItaliaPA 3.8.0.5

### Additional comments

La visualizzazione anomala del box dipendente dalla lunghezza del titolo inserito (titolo voce di menu).
Il testo ("titolo voce di menu") delle varie voci di menu non adatta i box.

**Comment by eshiol** [comment]
Il tipo di visualizzazione dipende dal toolkit

**Comment by eshiol** [comment]
Non riesco a occupare tutto lo spazio disponiile con il secondo link, ma riesco a distribuirlo su entrambi
![image](https://user-images.githubusercontent.com/12718836/36633794-a4eb21be-199b-11e8-843c-76cb37354dd2.png)
